### ISSUE TITLE
Host unreachable messages are flooding the log

### ISSUE THREAD

**Issue by Tom7320** [StyraHem/ShellyForHASS#119]
Hi

since the update to the current version "Host unreachable" messages are flooding the logs:

```
2019-12-14 14:53:34 WARNING (Thread-411) [pyShelly] Fail http GET: 192.168.205.101 /status [Errno 113] Host is unreachable
2019-12-14 14:53:37 ERROR (Poll) [pyShelly] Error http GET: http://192.168.205.101/settings, [Errno 113] Host is unreachable, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
2019-12-14 14:56:51 WARNING (Thread-468) [pyShelly] Fail http GET: 192.168.205.107 /status timed out
2019-12-14 14:57:37 WARNING (Thread-482) [pyShelly] Fail http GET: 192.168.205.101 /status timed out
2019-12-14 14:57:52 WARNING (Thread-486) [pyShelly] Fail http GET: 192.168.205.107 /status timed out
2019-12-14 14:58:16 WARNING (Thread-499) [pyShelly] Fail http GET: 192.168.205.106 /status timed out
2019-12-14 14:58:35 WARNING (Thread-500) [pyShelly] Fail http GET: 192.168.205.101 /status [Errno 113] Host is unreachable
2019-12-14 14:58:50 WARNING (Thread-504) [pyShelly] Fail http GET: 192.168.205.107 /status [Errno 113] Host is unreachable
2019-12-14 14:59:14 WARNING (Thread-517) [pyShelly] Fail http GET: 192.168.205.106 /status [Errno 113] Host is unreachable
2019-12-14 14:59:35 WARNING (Thread-518) [pyShelly] Fail http GET: 192.168.205.101 /status [Errno 113] Host is unreachable
2019-12-14 14:59:50 WARNING (Thread-523) [pyShelly] Fail http GET: 192.168.205.107 /status [Errno 113] Host is unreachable
2019-12-14 15:00:14 WARNING (Thread-536) [pyShelly] Fail http GET: 192.168.205.106 /status [Errno 113] Host is unreachable
2019-12-14 15:00:35 WARNING (Thread-537) [pyShelly] Fail http GET: 192.168.205.101 /status [Errno 113] Host is unreachable
2019-12-14 15:00:50 WARNING (Thread-542) [pyShelly] Fail http GET: 192.168.205.107 /status [Errno 113] Host is unreachable
```

The above mentioned devices are Shelly H&Ts. Thus it's normal that they are not reachable as long as temperature does not change...

Regards

Thorsten

**Comment by brighthouse** [comment]
Hi,
I am observing same behavior, at latest release of plugin Flood is not discovered at all, H&T works OK, but log is flooded with messages "Host is unreachable"

**Comment by chemelli74** [comment]
Hi,

same here.
But I noticed that once I removed my lovelace customizaion (/config/.storage/lovelace) and performed a restart, messages are gone and everything works as expected.
Running HA 0.103.0 on docker.

Regards,

Simone

**Comment by Tom7320** [comment]
But I can't just delete my entire Lovelace configuration?!?

**Comment by chemelli74** [comment]
> But I can't just delete my entire Lovelace configuration?!?

How many **manual** personalization you have ?
Usually the config is done by yaml config files, not from the UI; infact the first time you proceed you get a warning that tells you that from now on you have to handle manually all updates. isn't it ?

I had the file in place because I did a quick test long time ago. Nowdays I use yaml to configure things and I didn't lost anything just removing the file I told you about.

Simone

**Comment by Tom7320** [comment]
Well I only use GUI mode and I'm happy with it... :-)

**Comment by astrandb** [comment]
I also see this error on my H&T, every minute approximately 1500 times per 24h. I don't think it should be logged as an error since the H&T is asleep most of the time.

@chemelli74:  I am not prepared to delete my entire Lovelace configuration. I have invested considerable time in tuning it.

**Comment by bjornta** [comment]
My Shelly H&T (with fixed IP 192.168.50.201) causes the following error message in the log every second:

"Fail http GET: 192.168.50.201 /status [Errno 113] No route to host"
and this one every 10 minutes (ish):
"Fail http GET: 192.168.50.201 /status timed out"

The Shelly H&T is running on battery (without the USB power module), and works fine otherwise. It has "battery"-attribute = "92".

**Comment by chemelli74** [comment]
@bjornta, can you please retest with 0.1.6b6 ? Please update firmware to latest version as well.

Thank you,

Simone

**Comment by bjornta** [comment]
> @bjornta, can you please retest with 0.1.6b6 ? Please update firmware to latest version as well.
> 
> Thank you,
> 
> Simone

I installed 'master' branch through HACS. What's the safest way to upgrade to beta without losing my device IDs?

**Comment by chemelli74** [comment]
> I installed 'master' branch through HACS. What's the safest way to upgrade to beta without losing my device IDs?

Please enable "beta" on HACS and then download 1.0.6b6.
Also don't forget about latest firmware for the device.

Simone

**Comment by bjornta** [comment]
Looks good now. No clutter, at all, in the log.

Upgraded all Shelly1 to latest firmware. H&T did not want to upgrade, still running december-fw. Neither did the plug.

Upgraded HA from 103.6 to 104.3 while I was at it. Had to reboot a couple times to all integrations running.

logger-config:
   default: warning
   logs:
     homeassistant.core: error

After running for 15 minutes, before H&T called in it was (still) "unavailable".
Clicking on it in lovelace I had the option to remove it, saying:
"This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.
If the entity is no longer in use, you can clean it up by removing it."
Didn't.

As soon as the Shelly app reported an update from the H&T, after 30 minutes, it immediately became available in HA as well. Did not manually trigger the H&T to become online. Reported both temperature and humidity according to the app (although not rounded up to the nearest decimal).

Still no clutter in the log.

**Comment by Tom7320** [comment]
Seems to work! I'm looking forward for the final release! THX a lot!
