### ISSUE TITLE
Format error after Shelly CLoud upgrade

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#137]
Hi,

I switched from "shelly-**1**-eu.shelly.cloud" to "shelly-**9**-eu.shelly.cloud" as http://my.shelly.cloud indicate after today server upgrade.

Seens then, restarting HA shows the following error in my log:

```
2020-01-07 23:56:16 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 405, in _async_write_ha_state
    self.entity_id, state, attr, self.force_update, self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 987, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 724, in __init__
    ).format(entity_id)
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: .shelly_shsw_25_69339d_2_switch. Format should be <domain>.<object_id>
```

Am I alone ?
Thank you,

Simone

**Comment by hakana** [comment]
Should be fixed in 0.1.6 (Beta 4), please confirm.

**Comment by chemelli74** [comment]
After 12 hours of 0.1.6b6 I cannot see the isuse again.

I wait a few more hours and then I'll close the issue.

Simone

**Comment by chemelli74** [comment]
Log is clean.
I confirm bug is fixed.

Simone
