### ISSUE TITLE
error update loop (0.1.6-beta5)

### ISSUE THREAD

**Issue by fverschure** [StyraHem/ShellyForHASS#148]
File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 228, in _update_loop
    self.check_by_ip()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 170, in check_by_ip
    if block in self.blocks:
UnboundLocalError: local variable 'block' referenced before assignment
2020-01-15 20:02:31 ERROR (Poll) [pyShelly] Error update loop, local variable 'block' referenced before assignment, Traceback (most recent call last):

**Comment by astrandb** [comment]
I have same entries in my log

**Comment by mickaelmarin** [comment]
Me too https://github.com/StyraHem/ShellyForHASS/issues/145#issue-550149047

**Comment by fverschure** [comment]
fixed in 0.1.6-beta6
