### ISSUE TITLE
errors in log after shelly flood is woken up (0.1.5-beta5)

### ISSUE THREAD

**Issue by fverschure** [StyraHem/ShellyForHASS#149]
After a shelly flood is woken up the entities become available but following errors show up in the log:

2020-01-15 21:27:32 ERROR (Thread-1188) [pyShelly] Error update device status: 694A3A SHWT-1, 'bool' object has no attribute 'get', Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 103, in update_status_information
    dev.update_status_information(status)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 29, in update_status_information
    data = data.get(key, None) if data is not None else None
AttributeError: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 103, in update_status_information
    dev.update_status_information(status)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 29, in update_status_information
    data = data.get(key, None) if data is not None else None

**Comment by fverschure** [comment]
I have two shelly floods. Same happens with my other shelly flood, but then with another id in the log.

**Comment by hakana** [comment]
I will check with my flood

**Comment by fverschure** [comment]
still the same with beta 6 by the way.

**Comment by acirtautas** [comment]
Same with master

```
2020-01-16 01:58:37 ERROR (Thread-1915) [pyShelly] Error update device status: 76548D SHWT-1, 'bool' object has no attribute 'get', Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 103, in update_status_information
    dev.update_status_information(status)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 29, in update_status_information
    data = data.get(key, None) if data is not None else None
AttributeError: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 103, in update_status_information
    dev.update_status_information(status)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 29, in update_status_information
    data = data.get(key, None) if data is not None else None
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by chemelli74** [comment]
@fverschure, @acirtautas, please retest with 0.1.6b9 as this latest beta should fix the issue.

Thank you,

Simone

**Comment by fverschure** [comment]
@chemelli74 : tested with b9. Errors are no longer showing in the log. Everything is still working correctly. Please close this bug.
