### ISSUE TITLE
HA seems to DOS Shelly 2.5 after restart, logs flooded w/ timeouts

### ISSUE THREAD

**Issue by johntdyer** [StyraHem/ShellyForHASS#164]
After I restart everything is fine until I try to turn on a shelly 2.5.  Then all hell breaks loose and Home Assistant locks up and my logs are filled w/ these errors

```logs
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (SyncWorker_129) [pyShelly] Error http GET: http://192.168.100.60/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (SyncWorker_7) [pyShelly] Error http GET: http://192.168.100.60/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2020-01-24 09:44:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140711372036176] Client exceeded max pending messages [2]: 512
2020-01-24 09:44:42 ERROR (SyncWorker_5) [pyShelly] Error http GET: http://192.168.100.60/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
```

and I am unable to even reach the Shelly web interface because it goes unresponsive.   I have noticed from its ping replies that its seems to be being dos'ed, my guess by these get requests I see in the logs

```
64 bytes from 192.168.100.60: icmp_seq=1304 ttl=128 time=9355.544 ms
64 bytes from 192.168.100.60: icmp_seq=1305 ttl=128 time=9556.617 ms
64 bytes from 192.168.100.60: icmp_seq=1306 ttl=128 time=9334.989 ms
Request timeout for icmp_seq 1316
64 bytes from 192.168.100.60: icmp_seq=1308 ttl=128 time=9122.582 ms
Request timeout for icmp_seq 1318
Request timeout for icmp_seq 1319
Request timeout for icmp_seq 1320
Request timeout for icmp_seq 1321
Request timeout for icmp_seq 1322
64 bytes from 192.168.100.60: icmp_seq=1314 ttl=128 time=9814.342 ms
Request timeout for icmp_seq 1324
64 bytes from 192.168.100.60: icmp_seq=1315 ttl=128 time=10106.879 ms
64 bytes from 192.168.100.60: icmp_seq=1316 ttl=128 time=10346.397 ms
64 bytes from 192.168.100.60: icmp_seq=1317 ttl=128 time=9826.704 ms
64 bytes from 192.168.100.60: icmp_seq=1318 ttl=128 time=10794.783 ms
64 bytes from 192.168.100.60: icmp_seq=1319 ttl=128 time=10819.938 ms
Request timeout for icmp_seq 1330
Request timeout for icmp_seq 1331
64 bytes from 192.168.100.60: icmp_seq=1322 ttl=128 time=10397.163 ms
Request timeout for icmp_seq 1333
64 bytes from 192.168.100.60: icmp_seq=1324 ttl=128 time=10212.654 ms
64 bytes from 192.168.100.60: icmp_seq=1325 ttl=128 time=10022.794 ms
64 bytes from 192.168.100.60: icmp_seq=1326 ttl=128 time=10401.773 ms
64 bytes from 192.168.100.60: icmp_seq=1327 ttl=128 time=10083.396 ms
64 bytes from 192.168.100.60: icmp_seq=1328 ttl=128 time=9794.799 ms
64 bytes from 192.168.100.60: icmp_seq=1329 ttl=128 time=9931.297 ms
64 bytes from 192.168.100.60: icmp_seq=1330 ttl=128 time=9979.087 ms
64 bytes from 192.168.100.60: icmp_seq=1331 ttl=128 time=10166.073 ms
Request timeout for icmp_seq 1342
64 bytes from 192.168.100.60: icmp_seq=1332 ttl=128 time=11196.023 ms
64 bytes from 192.168.100.60: icmp_seq=1333 ttl=128 time=10193.895 ms
64 bytes from 192.168.100.60: icmp_seq=1334 ttl=128 time=10292.490 ms
64 bytes from 192.168.100.60: icmp_seq=1335 ttl=128 time=10267.298 ms
64 bytes from 192.168.100.60: icmp_seq=1336 ttl=128 time=10252.143 ms
64 bytes from 192.168.100.60: icmp_seq=1338 ttl=128 time=10195.507 ms
64 bytes from 192.168.100.60: icmp_seq=1339 ttl=128 time=10611.461 ms
Request timeout for icmp_seq 1350
Request timeout for icmp_seq 1351
Request timeout for icmp_seq 1352
Request timeout for icmp_seq 1353
Request timeout for icmp_seq 1354
64 bytes from 192.168.100.60: icmp_seq=1355 ttl=128 time=15.332 ms
64 bytes from 192.168.100.60: icmp_seq=1356 ttl=128 time=16.617 ms
64 bytes from 192.168.100.60: icmp_seq=1357 ttl=128 time=12.461 ms
64 bytes from 192.168.100.60: icmp_seq=1358 ttl=128 time=4.699 ms
```

I have the latest firmware on the Shelly
I have tried 1.5 and 1.6.b8 and both have the same results 
I am running Home Assistant 0.104.3
Server is Ubuntu 18 w/ Hassio, plenty of horsepower

my config is as follows

```
shelly:
  discovery: true
  #discover_by_ip:
  #  - '192.168.100.60'
```

I have also tried direct ip, as you can see its commented out above...

**Comment by johntdyer** [comment]
So a bit more information, it seems eventually Home Assistant does recover and so does the Shelly, but as soon as I try to interact w/ the Shelly 2.5 again ( eg turn it on or off ) the whole thing starts again and Home Assistant locks up, ping replies to the the shelly go through the roof, and the Shelly UI is unresponsive..   If I wait about 5 mins things calm down again, until I try to flip a switch

**Comment by chemelli74** [comment]
> 64 bytes from 192.168.100.60: icmp_seq=1304 ttl=128 time=9355.544 ms
> 64 bytes from 192.168.100.60: icmp_seq=1305 ttl=128 time=9556.617 ms
> 64 bytes from 192.168.100.60: icmp_seq=1306 ttl=128 time=9334.989 ms
> Request timeout for icmp_seq 1316
> 64 bytes from 192.168.100.60: icmp_seq=1308 ttl=128 time=9122.582 ms
> Request timeout for icmp_seq 1318
> Request timeout for icmp_seq 1319
> Request timeout for icmp_seq 1320
> Request timeout for icmp_seq 1321
> Request timeout for icmp_seq 1322
> 64 bytes from 192.168.100.60: icmp_seq=1314 ttl=128 time=9814.342 ms
> Request timeout for icmp_seq 1324
> 64 bytes from 192.168.100.60: icmp_seq=1315 ttl=128 time=10106.879 ms
> 64 bytes from 192.168.100.60: icmp_seq=1316 ttl=128 time=10346.397 ms
> 64 bytes from 192.168.100.60: icmp_seq=1317 ttl=128 time=9826.704 ms
> 64 bytes from 192.168.100.60: icmp_seq=1318 ttl=128 time=10794.783 ms

As far as you experience netowrk issues, we cannot do much.
Please fix your wifi and report back.

Simone

**Comment by chemelli74** [comment]
No update for 21 days, closing

Simone
