### ISSUE TITLE
turn_on() takes from 1 to 2 positional arguments but 3 were given when turning on Shelly Dimmer

### ISSUE THREAD

**Issue by maartenvang** [StyraHem/ShellyForHASS#219]
I have two Shelly Dimmer switches. They get detected just fine and show up in Lovelace with the correct state. I can turn off the dimmer with the switch in Lovelace. However, turning on a light with the toggle switch in lovelace does not work as expected. I get a toast message saying "turn_on() takes from 1 to 2 positional arguments but 3 were given".

The following shows up in my log file:
```
ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140133706427088] turn_on() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 590, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/light/__init__.py", line 243, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 615, in async_turn_on
    await self.hass.async_add_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/shelly/light.py", line 120, in turn_on
    self._dev.turn_on(brightness, color_temp)
TypeError: turn_on() takes from 1 to 2 positional arguments but 3 were given
```

I'm currently running Home assistant `v 0.106.6` and ShellyForHass `0.1.7-beta.1` installed through HACS.

**Comment by maartenvang** [comment]
I have checked out the master branch just to check if 0.1.7-beta.2 fixes the issue and it did. Thank you for your efforts!

**Comment by hakana** [comment]
Great!
