### ISSUE TITLE
Error while changing state of shelly dimmer

### ISSUE THREAD

**Issue by ttajmajer** [StyraHem/ShellyForHASS#222]
I have two shelly dimmers detected in HA. When I try to change the state of any of them the following error occurs. Other shelly devices work properly.

HA version:  0.106.6, running from docker in QNAP
ShellyForHASS version: 0.1.7 beta 2

`2020-03-15 16:44:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140126172751184] turn_on() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 243, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in async_turn_on
    await self.hass.async_add_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/shelly/light.py", line 120, in turn_on
    if color_temp < self._color_temp_min:
TypeError: turn_on() takes from 1 to 2 positional arguments but 3 were given
`

**Comment by ttajmajer** [comment]
The error is no longer present after HA is running for a longer time period.

**Comment by chemelli74** [comment]
> The error is no longer present after HA is running for a longer time period.

Closing the issue

Simone
