### ISSUE TITLE
0.1.7b3: log error at restart

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#227]
Sometime, at restart, I see the following log error:

```
2020-03-19 17:53:11 ERROR (Poll) [pyShelly] Error update loop, [Errno 1] Operation not permitted, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 233, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 133, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 233, in _update_loop
    self.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 133, in discover
    self._coap.discover()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 34, in discover
    self._socket.sendto(msg, (COAP_IP, COAP_PORT))
PermissionError: [Errno 1] Operation not permitted
```

Everything seems to work fine anyway.

Simone

**Comment by chemelli74** [comment]
Issue is not predictive, happens 1 time out of 4/5 restart.

Simone

**Comment by hakana** [comment]
Is it still working?

**Comment by chemelli74** [comment]
Didn't see it anymore after 10 reboot using 0.1.7b4.
Will wait a bit more to be 100% sure and then I'll close the issue.

Simone

**Comment by chemelli74** [comment]
Cannot reproduce with either 0.1.7b4 and 0.1.7b5.
Closing

Simone
