### ISSUE TITLE
pyShelly crashing

### ISSUE THREAD

**Issue by errolsancaktar** [StyraHem/ShellyForHASS#249]
Running home assistant in a docker, which I think is why its failing.  error below but it looks like its failing on trying to do an mDNS call.

`2020-04-05 23:09:11 INFO (MainThread) [pyShelly] Init  0.1.25
2020-04-05 23:09:11 INFO (MainThread) [custom_components.shelly] pyShelly, 0.1.25
2020-04-05 23:09:11 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/shelly/__init__.py", line 171, in start_up
    pys.start()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 107, in start
    self._coap.start()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 28, in start
    self._init_socket()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 50, in _init_socket
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
OSError: [Errno 19] No such device
`

**Comment by errolsancaktar** [comment]
When I try discover by ip I get this:

`2020-04-05 23:25:38 INFO (MainThread) [pyShelly] Init  0.1.25
2020-04-05 23:25:38 INFO (MainThread) [custom_components.shelly] pyShelly, 0.1.25
2020-04-05 23:25:38 DEBUG (Poll) [pyShelly] Start update loop, 0:01:00 sec
2020-04-05 23:25:38 DEBUG (MainThread) [pyShelly] Sending CoAP discover UDP
2020-04-05 23:25:38 DEBUG (Poll) [pyShelly] Sending CoAP discover UDP
2020-04-05 23:25:38 DEBUG (MainThread) [pyShelly] Check add device by host 172.16.0.62 IP-addr
2020-04-05 23:25:38 DEBUG (MainThread) [pyShelly] Add device by host 172.16.0.62 IP-addr
2020-04-05 23:25:48 DEBUG (CoAP) [pyShelly] CoAP msg: 192.168.16.2 b'P\x01\x00\n\xb3cit\x01d\xff'
2020-04-05 23:25:48 DEBUG (CoAP) [pyShelly] CoAP msg: 1 192.168.16.2 bytearray(b'P\x01\x00\n\xb3cit\x01d\xff')
2020-04-05 23:25:48 DEBUG (CoAP) [pyShelly] CoAP msg: 192.168.16.2 b'P\x01\x00\n\xb3cit\x01d\xff'
2020-04-05 23:25:48 DEBUG (CoAP) [pyShelly] CoAP msg: 1 192.168.16.2 bytearray(b'P\x01\x00\n\xb3cit\x01d\xff')
2020-04-05 23:26:38 DEBUG (Poll) [pyShelly] http://172.16.0.62/settings
2020-04-05 23:26:38 DEBUG (Poll) [pyShelly] Fail http GET: 172.16.0.62 /settings [Errno 104] Connection reset by peer
2020-04-05 23:26:38 INFO (Poll) [pyShelly] Error adding device, 172.16.0.62
2020-04-05 23:26:38 DEBUG (Poll) [pyShelly] Sending CoAP discover UDP
2020-04-05 23:26:38 DEBUG (CoAP) [pyShelly] CoAP msg: 192.168.16.2 b'P\x01\x00\n\xb3cit\x01d\xff'
2020-04-05 23:26:38 DEBUG (CoAP) [pyShelly] CoAP msg: 1 192.168.16.2 bytearray(b'P\x01\x00\n\xb3cit\x01d\xff')`

**Comment by errolsancaktar** [comment]
curling the /settings I get a good response:

`{"device":{"type":"SHRGBW2","mac":"<>","hostname":"shellyrgbw2-661ACF","num_outputs":4},"wifi_ap":{"enabled":false,"ssid":"shellyrgbw2-661ACF","key":""},"wifi_sta":{"enabled":true,"ssid":"SanNet","ipv4_method":"static","ip":"172.16.0.62","gw":"172.16.0.1","mask":"255.255.255.0","dns":null},"wifi_sta1":{"enabled":false,"ssid":null,"ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"mqtt": {"enable":true,"server":"<>","user":"<>","id":"<>","reconnect_timeout_max":60.000000,"reconnect_timeout_min":2.000000,"clean_session":true,"keep_alive":60,"max_qos":0,"retain":true,"update_period":30},"coiot": {"update_period":15},"sntp":{"server":"time.google.com","enabled":true},"login":{"enabled":false,"unprotected":false,"username":"admin","password":"admin"},"pin_code":"","name":"","fw":"20200309-104453/v1.6.0@43056d58","factory_reset_from_switch":true,"discoverable":true,"build_info":{"build_id":"20200309-104453/v1.6.0@43056d58","build_timestamp":"2020-03-09T10:44:53Z","build_version":"1.0"},"cloud":{"enabled":false,"connected":false},"timezone":"<>,"tzautodetect":true,"tz_utc_offset":-21600,"tz_dst":true,"tz_dst_auto":true,"time":"23:27","unixtime":1586129258,"hwinfo": {"hw_revision":"prod-190410b","batch_id":1},"mode":"color","dcpower":0,"lights":[{"ison":true,"red":255,"green":0,"blue":0,"white":0,"gain":100,"effect":0,"default_state":"last","auto_on":0.00,"auto_off":0.00,"schedule":false,"btn_type":"edge","btn_reverse":0,"schedule_rules":[]}]}`

**Comment by chemelli74** [comment]
> 23:26:38 DEBUG (Poll) [pyShelly] http://172.16.0.62/settings 2020-04-05 23:26:38 DEBUG (Poll) [pyShelly] **Fail http GET: 172.16.0.62 /settings [Errno 104] Connection reset by peer** 2020-04-05 23:26:38 INFO (Poll) [pyShelly] Error adding device, 172.16.0.62 2020-04-05 23:26:38 DEBUG (Poll) [pyShelly] Sending CoAP discover UDP 2020-04-05 23:26:38 DEBUG (CoAP) [pyShelly] CoAP msg: 192.168.16.2 b'P\x01\x00\n\xb3cit\x01d\xff' 2020-04-05 23:26:38 DEBUG (CoAP) [pyShelly] CoAP msg: 1 192.168.16.2 bytearray(b'P\x01\x00\n\xb3cit\x01d\xff')`

Seems your HA points to a different ip that the Shelly.
Can you please try to "curl -s http://172.16.0.62/settings" from HA console ?

Simone

P.S.> I'm on docker and everything works fine here ;-)

**Comment by errolsancaktar** [comment]
turns out this exposed another issue with my docker-compose.  its resolved now.  i had the app bridge network configured a little off.
