### ISSUE TITLE
Rollers detected as relays

### ISSUE THREAD

**Issue by uspino2** [StyraHem/ShellyForHASS#26]
Some of my Shelly 2.5 devices appear as double switches. They are identified as relays, not rollers. I suspect it has to do with the wifi signal quality: if the Shelly take a little longer to respond to the http call, it ends up showing up as relay instead of roller. Is there a way to add a small delay in the discovery routine? This is what I get for each roller wrongly identified as relay: 
```
Wed Jun 05 2019 18:46:41 GMT+0200 (Central European Summer Time)
Error http GET: http://10.10.10.201/settings [Errno 113] Host is unreachable Traceback (most recent call last):
  File "/config/deps/lib/python3.7/site-packages/pyShelly/__init__.py", line 169, in http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
Traceback (most recent call last):
  File "/config/deps/lib/python3.7/site-packages/pyShelly/__init__.py", line 169, in http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
```

**Comment by hakana** [comment]
It must be an issue in your network, it is not a time out it is host unreachable. Is this when you connect/power up a Shelly or is it also when the Shelly have been on for a while?
