### ISSUE TITLE
[BUG] Entity format issue on 0.110.b0

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#303]
## Environment

- ShellyForHASS release with the issue: 0.1.9.b1
- Last working ShellyForHASS release (if known): -
- Home Assistant Core release with the issue: 0.110.b0
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

Log error reported, no side effect discovered so far

## Steps to Reproduce

Update to 0.110.b0

## Expected behavior

No error logged

## Traceback/Error logs

```txt
2020-05-15 01:14:31 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 413, in _async_write_ha_state
    self.entity_id, state, attr, self.force_update, self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1000, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 742, in __init__
    f"Invalid entity id encountered: {entity_id}. "
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: .shelly_shsw_25_xxxxxx_1_current_consumption. Format should be <domain>.<object_id>
```

**Comment by chemelli74** [comment]
Fixed by latest beta,

Simone
