### ISSUE TITLE
[BUG] Shelly plug S can't be controlled

### ISSUE THREAD

**Issue by daha76** [StyraHem/ShellyForHASS#311]
## Environment

- ShellyForHASS release with the issue: 0.1.8
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 0.110.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised

## Describe the bug
Can't switch on/off the plug

## Steps to Reproduce
put shelly plugs entity into lovelace and try to controll on/off state

## Expected behavior
on/off state is properly controlled

## Traceback/Error logs
```txt
2020-06-01 23:43:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1823573392] 'switch.shelly_shplg_s_376ba4'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 419, in entity_service_call
    entity_ids.remove(entity.entity_id)
KeyError: 'switch.shelly_shplg_s_376ba4'
```

**Comment by chemelli74** [comment]
Please try updating to latest build, 1.0.9.b2 and report back.

Simone

**Comment by daha76** [comment]
A just made an update and I also restarted the RPi 3B+ but still the same error.

**Comment by chemelli74** [comment]
Please report firmware version of the Plug.
Did you upgrade plugin to 0.1.9b2 ? If so post a new trace error log.

Simone

**Comment by daha76** [comment]
Error was the same. But I made a complete clean of the Shelly integration, I deleted everything also in config files and reinstalled it again. So far it works, so maybe something wrong happens while I was updating Hassio or I don't know. I think it can be closed, sorry.
