### ISSUE TITLE
Shelly devices disconnected

### ISSUE THREAD

**Issue by rafa67** [StyraHem/ShellyForHASS#32]
I have two Shelly 2.5 working as Rolling Shutter and other two Shelly 1 to control two lamps.
They were working well with the component but since last updates there are problems with all of them. Apparently they are discovered and integrated in HA but every minute they are unavailable and it is impossible to get the state. For example, sometimes the command turn_on is working over the switch but the state remains off, and the command turn_off doesn’t work.
I have updated to the 0.95.4 version of HA and I think that one of the last updates has produced this issue.
Do you have any information about it?
Thanks a lot.

**Comment by hakana** [comment]
I will check on monday

**Comment by AtticusG3** [comment]
This sounds like the bug I experienced with this when i was using it. I posted about it in the shelly support group page on facebook but got no response so I migrated back to MQTT.

**Comment by gaggio** [comment]
I updated to 0.0.15, and the issue is still there, but changed behavior: shellies are now unavailable for longer periods of time, and when they come back, the stay available for the same time (a minute or so), see plot below, 

![screenshot 65](https://user-images.githubusercontent.com/38132917/61855293-1b827880-aec0-11e9-9e15-8300d5e9609b.jpg)

**Comment by davtes77** [comment]
I have the same problem, but only with shelly 2.5. My shelly 2 works correctly.
All the shelly 2.5 goes unavailable/available at the same time.
Please note that only the light entities are affected, other entities like current, wifi, uptime, sensors are ok.

![shelly_bug](https://user-images.githubusercontent.com/46325108/62389232-918d7c00-b55f-11e9-8e83-ad5c456c1dc2.JPG)

**Comment by jonydebu** [comment]
Same problem here , with shelly 2.5 , hassio 0.97 on QNAP virtualbox  . 
Shelly1 , no problem at all .

**Comment by patrul** [comment]
Similar problem here. I have 3 RGBW2 and 4 2.5

My logs when all devices show as unavailable, but logs are related to only one of them. It seems when any problem is detected, stop working and impacts on all Shelly devices:

```
2019-08-26 13:43:06 ERROR (Thread-2) [pyShelly] Error http GET: http://192.168.1.157/color/0 [Errno 113] Host is unreachable Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 198, in http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 198, in http_get
    conn.request("GET", url, None, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable
```

**Comment by hdueo** [comment]
28/5000
similar problem for me too. Today I updated HA to version 0.98.4 and at the same time I replaced the old router with a fritz!box. Now shelly disconnects 5 minutes after restarting HA

**Comment by hakana** [comment]
Try igmp_fix flag

**Comment by hdueo** [comment]
thank you. With this flag it seems to work

**Comment by davtes77** [comment]
I confirm, it works! No more disconnections from all my shellyes 2.5 in the past 24 hours.
Thank you

**Comment by gufi666** [comment]
Hi, I have the same problem. Home Assistent its new for me so please tell me where I should search this igmp_fix_flag ??
