### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'custom_components.shelly4hass.logbook'

### ISSUE THREAD

**Issue by rgogada** [StyraHem/ShellyForHASS#342]
## Environment

- ShellyForHASS release with the issue: 0.1.9-b2
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 112
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Traceback/Error logs

```txt

```

**Comment by rgogada** [comment]
2020-07-03 12:07:23 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing shelly/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 322, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.shelly4hass.logbook'

**Comment by chemelli74** [comment]
Please fill the template.

Simone

**Comment by chemelli74** [comment]
Please remove, reboot and reinstall the plugin.
"logbook.py" is not part of this plugin or the underlining library.

Simone

**Comment by rgogada** [comment]
@chemelli74 that worked. thanks.
