### ISSUE TITLE
[BUG]Shelly Devices (RGBW2) Disconnect from ShellyForHASS While Remaining Active on Local Network

### ISSUE THREAD

**Issue by ericvitale** [StyraHem/ShellyForHASS#347]
## Environment

- ShellyForHASS release with the issue: 0.1.9 beta.2
- Last working ShellyForHASS release (if known): Not known.
- Home Assistant Core release with the issue: At least 0.111.0 - 0.112.4
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Describe the bug

I have 14 shelly devices on my network and configured within Home Assistant.  Of which, two are RBGW2 devices which are constantly getting disconnected from the Home Assistant. I don't have this issue with my other devices (Shelly 1, Shelly 1PM, and Shelly 2.5). All devices are configured using the new MQTT feature. You can see the settings of each for the MQTT in the images below. Once the devices become disconnected to Home Assistant I can still access them directly from their IP address and control them (outside of Home Assistant) and when I restart Home Assistant they reconnect without having to restart the shelly device. Restarting the shelly devices does not help, they only reconnect when I restart home assistant.

## Steps to Reproduce

None really, just connect an RGBW2 device, wait... Sometimes a few hours, sometimes a day.

## Expected behavior

Device stays connected.

## Screenshots

Firmware Page
<img width="965" alt="Shelly_rgbw_2_125" src="https://user-images.githubusercontent.com/8474048/87322086-fd5fbf00-c4fa-11ea-9121-112072663cc2.png">
<img width="969" alt="shelly_rgbw_2_130" src="https://user-images.githubusercontent.com/8474048/87322087-fd5fbf00-c4fa-11ea-98dd-d7deff2c04a6.png">

MQTT Settings
<img width="818" alt="mqtt_125" src="https://user-images.githubusercontent.com/8474048/87322117-081a5400-c4fb-11ea-8f40-7702f4669b29.png">
<img width="838" alt="mqtt_130" src="https://user-images.githubusercontent.com/8474048/87322118-081a5400-c4fb-11ea-9674-d51003f3efef.png">

HA View
<img width="340" alt="ha_125" src="https://user-images.githubusercontent.com/8474048/87322152-10728f00-c4fb-11ea-96cb-929dc6340425.png">
<img width="350" alt="ha_130" src="https://user-images.githubusercontent.com/8474048/87322153-10728f00-c4fb-11ea-9ad3-19f229563e89.png">

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
Have you tried the igmp_fix setting? Any errors in HA logs?

**Comment by ericvitale** [comment]
I’ll try igmp_fix. Didn’t think it would help with mqtt.

**Comment by ericvitale** [comment]
I've turned on igmp_fix. I'll see how things go. As for the logs, nothing in there related to my RGBW devices. None of the IP addresses below are for the RGBW devices.

2020-07-13 11:18:39 INFO (MainThread) [pyShelly] Init  0.1.30
2020-07-13 11:18:39 INFO (MainThread) [custom_components.shelly] pyShelly, 0.1.30
2020-07-13 13:01:55 ERROR (SyncWorker_79) [pyShelly] Error http GET: http://10.20.1.122/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-13 16:38:02 ERROR (SyncWorker_5) [pyShelly] Error http GET: http://10.20.1.122/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-13 21:23:57 ERROR (SyncWorker_26) [pyShelly] Error http GET: http://10.20.1.124/relay/0?turn=on, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 57, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 57, in shelly_http_get
2020-07-14 09:51:56 ERROR (SyncWorker_29) [pyShelly] Error http GET: http://10.20.1.127/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-14 11:28:46 ERROR (SyncWorker_40) [pyShelly] Error http GET: http://10.20.1.122/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-14 11:47:46 ERROR (SyncWorker_8) [pyShelly] Error http GET: http://10.20.1.122/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-14 13:15:39 ERROR (SyncWorker_10) [pyShelly] Error http GET: http://10.20.1.121/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-14 13:18:03 ERROR (SyncWorker_16) [pyShelly] Error http GET: http://10.20.1.127/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-14 14:55:35 ERROR (SyncWorker_74) [pyShelly] Error http GET: http://10.20.1.127/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
2020-07-14 20:13:27 ERROR (SyncWorker_2) [pyShelly] Error http GET: http://10.20.1.127/relay/0?turn=off, timed out, Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get

**Comment by ericvitale** [comment]
No luck with that settings. Devices have gone offline in home assistant, but still available by IP directly. Here are logs looking for 'shelly', filtering on pyShelly returns more of what was above but nothing related to those devices.

2020-07-13 11:18:38 INFO (MainThread) [homeassistant.setup] Setting up shelly
2020-07-13 11:18:38 INFO (MainThread) [homeassistant.setup] Setup of domain shelly took 0.3 seconds.
2020-07-13 11:18:38 INFO (MainThread) [custom_components.shelly] Starting shelly, 0.1.9-b2
2020-07-13 11:18:39 INFO (MainThread) [custom_components.shelly] pyShelly, 0.1.30
2020-07-13 11:18:43 INFO (MainThread) [homeassistant.components.switch] Setting up switch.shelly
2020-07-13 11:18:43 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.shelly
2020-07-13 11:18:43 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.shelly
2020-07-13 11:18:44 INFO (MainThread) [homeassistant.components.light] Setting up light.shelly
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 57, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 57, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 56, in shelly_http_get
****

**Comment by thesonandheir** [comment]
I'm having this issue with two Shelly 1's on my network. They are reporting as unavailable to HA but still available (for a short time) through the Shelly app and static IP web interface. After a while one or both of them will report as 'device offline' and will require a power reset by means of the circuit protection device (MCB).

I have downgraded the Shelly 1 firmware to 1.62 and still same issue. 

Note - my HA/Shelly/ShellyForHass setup has been working perfectly for a while until I decided to upgrade my network to a Huawei Q2 Pro mesh server which is when the issue has arisen.

**Comment by ericvitale** [comment]
Not sure it is the same issue as I don't have the restart the shelly devices, I have to restart HA to get them working.

**Comment by chemelli74** [comment]
>  None of the IP addresses below are for the RGBW devices.

This is your main issue.
There is something in between HA and the RGBW device that change the ip.
You have more vlan ? a Proxy ?
Plaese describe in details your network.

Simone

**Comment by chemelli74** [comment]
Hi all, just to inform that after 3 weeks of inactivity on thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by ericvitale** [comment]
Sorry, I didn't see your reply. Thanks for getting back to me.

Ah, my network details. I have a pretty complex network as I have a lot of IoT devices requiring a network connection (along with others that use zigbee or z-wave). 

I have a very segregated network, but all of my IoT devices are on the same network which also includes my Home Assistant server. I have my Home Assistant sever on the same VLAN as my IoT devices as I was unable to overcome a few issues with them being on separate networks. For example, Amazon Alexa can't discover any Home Assistant devices if it is on a different VLAN.

RBGW2 - A: 10.20.1.125
RBGW2 - B: 10.20.1.130
HA Server: 10.20.1.254

Before I had the IoT devices and HA server on the same VLAN I did use the shelly proxy. I don't use it anymore as they are on the same network, even though I also now use the mqtt settings for the devices.

**Comment by chemelli74** [comment]
Issue related to specific network config.
Closing.

Simone

**Comment by ericvitale** [comment]
Um, ok. Specific network config that only impacts my RGBW2 devices and none of my Shelly One, Shelly 1PM, or Shelly 2.5. I get you software is free. I responded a month ago with no response until now.

**Comment by hakana** [comment]
Right now we working on 1.8 fw update. We will get back to this after that.
