### ISSUE TITLE
[BUG] Avoid running multiple Zeroconf instances

### ISSUE THREAD

**Issue by chemelli74** [StyraHem/ShellyForHASS#370]
## Environment

- ShellyForHASS release with the issue: 01.9
- Last working ShellyForHASS release (if known): - 
- Home Assistant Core release with the issue: 0.113.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Describe the bug

Zeroconf errors due to multiple instances. This is also a cause for high CPU

## Steps to Reproduce

Check [0.113.0 - Zeroconf errors](https://github.com/home-assistant/core/issues/38248)

## Expected behavior

No error and normal CPU usage

## Traceback/Error logs

```txt
2020-07-23 17:53:13 WARNING (zeroconf-ServiceBrowser__http._tcp.local._5358) [zeroconf] Error sending through socket 25
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2792, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 22] Invalid argument

2020-07-26 08:24:40 WARNING (zeroconf-ServiceBrowser__http._tcp.local._5358) [zeroconf] Error sending through socket 25
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2792, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 19] No such device
```

## Additional context

Fix should be part of the library as well: https://github.com/StyraHem/pyShelly/issues/27

**Comment by chemelli74** [comment]
Issue should be fixed in library [pyShelly](https://github.com/StyraHem/pyShelly/issues/27)

Simone
