### ISSUE TITLE
ERROR (CoAP) [pyShelly] Error receive CoAP after firmware upgrade

### ISSUE THREAD

**Issue by Ras195** [StyraHem/ShellyForHASS#373]
After I updated the firmware of my Shellys:

Shelly 1pm: updated to 20200812-092009/v1.8.0@8acf41b0
Shelly T&H: 20200812-091311/v1.8.0@8acf41b0

I start receiving these errors from Hassio:

2020-08-12 17:20:30 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 183, in _loop
    ipaddr, 'CoAP-msg', payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/relay.py", line 50, in update

The problem should be related to the Shelly 1pm because I can't see on hassio the total and the current consumption.
At the moment the Shelly T&H seems to still works good.

**Comment by astrandb** [comment]
Same problem here with various Shelly models after firmware update to 1.8.0
```
File "/srv/homeassistant/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
```
This error is logged every 15 sec for each device so I hold further firmware upgrades...

**Comment by Ras195** [comment]
> Same problem here with various Shelly models after firmware update to 1.8.0
> 
> ```
> File "/srv/homeassistant/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
>     self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
> TypeError: type NoneType doesn't define __round__ method
> ```
> 
> This error is logged every 15 sec for each device so I hold further firmware upgrades...

yes, I got the same:

  File "/usr/local/lib/python3.7/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method

but now I can see values about total and the current consumption on my Shelly 1pm

**Comment by ezaton** [comment]
Same concept. This case - Shelly 2.5:
2020-08-12 22:56:15 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/switch.py", line 46, in update
    self._update(state > 0, {'last_event' : self.last_event,
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Cover states changes between 'None' and their actual position.

**Comment by d-edge82** [comment]
Same here.
broke all my switches automations (detached switch, switch status on-> turn on zigbee lamp)
the switch status takes 2 minutes to be updated on HA

**Comment by coen17st** [comment]
same to me! switches switch very slowly or sometimes not at all

`ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/switch.py", line 46, in update
    self._update(state > 0, {'last_event' : self.last_event,`

**Comment by chemelli74** [comment]
Please check #366 

Simone

**Comment by Soylor** [comment]
I did solve it using rest api (DDD) from now
changed my configuration.yaml to get that
Now everithing work without selly integration component.
