### ISSUE TITLE
[BUG] Error receive CoAP (TypeError: '>' not supported between instances of 'NoneType' and 'int')

### ISSUE THREAD

**Issue by andrea-mattioli** [StyraHem/ShellyForHASS#374]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 0.114.0 and 0.113.X
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker

## Traceback/Error logs

```  Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 53, in update
    self.info_values[INFO_VALUE_SWITCH] = switch_state > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

```

**Comment by sylvaing** [comment]
I have the same error since update of shelly firmware I think, I have many error "TypeError: '>' not supported between instances of 'NoneType' and 'int'"

**Comment by robinostlund** [comment]
Version 1.8 of shelly is not supported yet, check #366

**Comment by sylvaing** [comment]
@robinostlund ok thank you very much !
