### ISSUE TITLE
Shelly 3EM values

### ISSUE THREAD

**Issue by MatSterner** [StyraHem/ShellyForHASS#375]
I updated both the firmware of the Shelly  and Home Assistant at the same time so I don't know if the issue is with the integration or Home Assistant.

The current_consumtion entities of Shelly 3 em goes down to zero all the time. It shows a value for a few seconds then go back to 0W for about 30 seconds (havn't clocked it) then it goes back to zero almost instantly. The current can show 10A but the consumtion show 0W

In the log I see this

```
Logginformation (ERROR)
Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/coap.py:191
First occurred: 13 augusti 2020 22:43:22 (22650 occurrences)
Last logged: 14:12:34
![Screem](https://user-images.githubusercontent.com/48876968/90248622-58a60980-de39-11ea-9d43-e0dc76f502a7.JPG)


Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method

Logginformation (ERROR)
Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/coap.py:191
First occurred: 13 augusti 2020 22:43:18 (33340 occurrences)
Last logged: 14:12:34

Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 53, in update
    self.info_values[INFO_VALUE_SWITCH] = switch_state > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

As you can see I got 30000+ errors since yesterday. The values from my Shelly 1PM seems OK

**Comment by chemelli74** [comment]
Are you running firmware 1.8 right ?

Simone

**Comment by MatSterner** [comment]
Yes. Just saw that 1.8.1 is released. I updated now but seems to be same
problem.

Den fre 14 aug. 2020 15:02Simone Chemelli <notifications@github.com> skrev:

**Comment by chemelli74** [comment]
Check #366

Simone
