### ISSUE TITLE
Switches in HA turn off immediately

### ISSUE THREAD

**Issue by durrav** [StyraHem/ShellyForHASS#376]
I have two Shelly Dimmers (1st gen). When turning on a light through HA, the switch in HA turns off immediately. The actual lamp stays on and is also on in the dimmer's web interface. Since it turns off so quickly I cannot  adjust the brightness at all. Same behavior on both dimmers. I noticed this today but the issue can have been present for a few days. I hadn't made any updates prior to the issue, but I have tried to update HA to the latest version (0.114.0) and reinstalled the integration through HACS, but still same. I also restarted the dimmers through the web interface but still same.

The log shows a lot of errors like these:

2020-08-14 14:47:36 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/switch.py", line 46, in update
    self._update(state > 0, {'last_event' : self.last_event,
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2020-08-14 14:47:51 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/switch.py", line 46, in update
    self._update(state > 0, {'last_event' : self.last_event,
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2020-08-14 14:47:51 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/switch.py", line 46, in update
    self._update(state > 0, {'last_event' : self.last_event,
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by chemelli74** [comment]
Are you running firmware 1.8 right ?

Simone

**Comment by durrav** [comment]
> Are you running firmware 1.8 right ?
> 
> Simone

Yes I am.

**Comment by chemelli74** [comment]
Check #366

Simone
