### ISSUE TITLE
[BUG] TypeError: type NoneType doesn't define __round__ method

### ISSUE THREAD

**Issue by entropie** [StyraHem/ShellyForHASS#378]
## Environment

- ShellyForHASS release with the issue:  0.1.9
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: Home Assistant 0.113.3
- Operating environment (Home Assistant/Supervised/Docker/venv): docker

## Describe the bug

Flooding errors in the log.

## Steps to Reproduce

Go Integration page in HA. Add Shelly Via "+".

## Expected behavior

No errors in log.

## Screenshots

![2020-08-14-214210_842x418_scrot](https://user-images.githubusercontent.com/3646/90286933-1b606c80-de77-11ea-8a96-830c1a61b735.png)

## Traceback/Error logs

```txt
2020-08-14 19:45:34 INFO (MainThread) [custom_components.shelly] Starting shelly, 0.1.9
2020-08-14 19:45:34 INFO (MainThread) [pyShelly] Init  0.1.33
2020-08-14 19:45:35 INFO (MainThread) [custom_components.shelly] pyShelly, 0.1.33
2020-08-14 19:45:45 INFO (MainThread) [homeassistant.components.switch] Setting up switch.shelly
2020-08-14 19:45:45 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.shelly
2020-08-14 19:45:45 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.shelly entity: switch.shelly_shplg_s_801138
2020-08-14 19:45:45 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.shelly entity: sensor.shelly_shplg_s_801138_current_consumption
2020-08-14 19:45:45 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-14 19:45:55 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.shelly entity: sensor.shelly_shplg_s_801138_total_consumption

2020-08-14 19:46:00 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method

```

## Additional context

My only device is a (new, freshly firmware updated) shelly plug s.

**Comment by chemelli74** [comment]
Again, issue is related to firmware 1.8.

Check #366 

Simone
