### ISSUE TITLE
[BUG] ShellyForHASS shows values than goes to 0 3EM and EM

### ISSUE THREAD

**Issue by VladoPortos** [StyraHem/ShellyForHASS#380]
## Environment

- ShellyForHASS release with the issue:  Latest 0.1.9
- Last working ShellyForHASS release (if known):  0.1.9
- Home Assistant Core release with the issue: 0.115 ( 0.114  as well ) 
- Operating environment (Home Assistant/Supervised/Docker/venv): HA in Docker on Unraid server

## Describe the bug

I think something changed in firmware for Shelly 3EM and Shelly EM because a week ago it worked prefectly fine. Now when I go to HASS and see my power meter widgets, for a few seconds they show correct values and than goes to 0 on all of them ( 1x 3EM and 2x EM ), after some while it show the values for few seconds and than goes to 0 again.... 

## Steps to Reproduce

Unknown, only think I have done is updated Shelly firmware to the latest. Tried to downgrade HASS but no change....

## Expected behavior

Show correct values all the time, without dropping to 0

## Traceback/Error logs

```txt
020-08-16 21:17:04 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-08-16 21:17:16 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 38, in initialize
    await scanner.async_scan(None)
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 61, in async_scan
    await self._process_entries(entries)
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 85, in _process_entries
    result for result in await asyncio.gather(*tasks) if result is not None
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 120, in _process_entry
    info.update(await info_req)
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 120, in _process_entry
    info.update(await info_req)
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 120, in _process_entry
    info.update(await info_req)
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 138, in _fetch_description
    xml = await resp.text()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1014, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 229: invalid start byte
2020-08-16 21:17:23 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:23 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:23 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:23 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:23 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:23 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:23 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:30 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:31 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:31 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:31 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:31 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:31 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:31 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:45 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:46 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:46 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:46 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:46 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:46 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:17:46 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:00 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:01 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:01 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:01 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:01 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:01 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:01 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:15 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:16 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:16 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:16 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:16 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:16 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:16 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:30 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method
2020-08-16 21:18:31 ERROR (CoAP) [pyShelly] Error receive CoAP
```

**Comment by coin** [comment]
I'm having the same behavior with my setup!
It is the first time I'm using the ShellyForHASS and just added the 3EM to my distribution board, so I didn't know what to expect.

**Comment by stevearmitage** [comment]
This is the same CoAP issue as detailed in https://github.com/StyraHem/ShellyForHASS/issues/366

I downgraded my Shelly EM's back to the July release and the zero's have gone - see my graph screenshot.
<img width="93" alt="Screenshot 2020-08-17 at 12 38 11" src="https://user-images.githubusercontent.com/29444933/90357721-892eb300-e086-11ea-8ca0-0e5e9802c537.png">

Use this link to change to an older version. 
https://www.shelly-support.eu/index.php?shelly-firmware-archive/

The team are working on updating the Shelly For Hass integration.

**Comment by chemelli74** [comment]
> This is the same CoAP issue as detailed in #366

Exactly.
Closing

Simone
