### ISSUE TITLE
[BUG] shelly coap message errors

### ISSUE THREAD

**Issue by mani76** [StyraHem/ShellyForHASS#383]
## Environment

- ShellyForHASS release with the issue:  0.1.9
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 0.114.2
- Operating environment (Home Assistant/Supervised/Docker/venv):  venv
## Describe the bug

After updating latest shelly firmware, home-assistant and HACS 1.4.1 all connected shelly devices stopped to work.
Error message is shown in the HA logs and all shelly devices are disabled in the user interface.

New error messages are shown continuously.

By using Shelly mobile app I am able to use devices normally.

Affects at least: Shelly 2pm, Shelly dimmer 

## Traceback/Error logs

2020-08-18 18:38:02 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyShelly/coap.py", line 183, in _loop
    ipaddr, 'CoAP-msg', payload)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyShelly/switch.py", line 46, in update
    self._update(state > 0, {'last_event' : self.last_event,
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by mani76** [comment]
duplicate
