### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by YelsewB** [StyraHem/ShellyForHASS#394]
Suddenly(Since i came back from holidays) my homeassisntent.log is getting spammed with the following stacktrace:

```2020-08-26 11:44:31 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/switch.py", line 46, in update
    self._update(state > 0, {'last_event' : self.last_event,
TypeError: '>' not supported between instances of 'NoneType' and 'int'```

**Comment by YelsewB** [comment]
Fund the same in another issue from 2 weeks ago. Will subscribe on that.
