### ISSUE TITLE
[BUG] Shelly integration breaks HA internet connectivity

### ISSUE THREAD

**Issue by puttyman** [StyraHem/ShellyForHASS#401]
## Environment

- ShellyForHASS release with the issue: 
Home Assistant 0.114.1
- Last working ShellyForHASS release (if known): 
I have tried latest (0.19), 0.18 and 0.17. They all have the same issue. I am new to this integration.
- Home Assistant Core release with the issue: 
HassOS 4.12 installed on promox using https://github.com/whiskerz007/proxmox_hassos_install
- Operating environment (Home Assistant/Supervised/Docker/venv): 
As above running as a promox VM, with 2core, 4gb memory - physical cpu is an i7-4790
## Describe the bug
After installing the integration through HACS everything will work fine for a little while. Around 10-30s after all integration which requires internet connectivity stops working e.g. AC/Tuya over cloud. See screenshot below for logs:

![Image of Yaktocat](https://i.ibb.co/k5xbCdr/halogs.png)

## Steps to Reproduce
1. Install the integration through HACS
2. Devices are discovered.
3. Do any action on HA that requires internet connectivity e.g (switch on ac/light hooked to cloud, download an addon)
4. Action will timeout. (can be intermittent)
5. Check HA logs.

1. After the above.
2. Restart HA.
3. Many integration would be in yellow "Home Assistant is starting, not everything may be avaialble yet"

## Expected behavior
- HA integrations to start with no issues.

## Screenshots
![Image of Yaktocat](https://i.ibb.co/THr26W5/dashboard.png)

## Traceback/Error logs

```txt
2020-08-29 12:13:02 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_temperature (c:24eb3a3ae99d11ea9bf91df27fd5391a): entity_id=['climate.living'], temperature=23.0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensibo/climate.py", line 320, in async_set_temperature
    await self._client.async_set_ac_state_property(
  File "/usr/local/lib/python3.8/site-packages/pysensibo/__init__.py", line 77, in async_set_ac_state_property
    resp = yield from self._session.patch(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1324, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/sensibo/climate.py", line 320, in async_set_temperature
    await self._client.async_set_ac_state_property(
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2020-08-29 12:13:07 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.living is taking over 10 seconds
2020-08-29 12:13:07 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.bedroom is taking over 10 seconds
2020-08-29 12:13:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.living fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensibo/climate.py", line 398, in async_update
    data = await self._client.async_get_device(self._id, _FETCH_FIELDS)
  File "/usr/local/lib/python3.8/site-packages/pysensibo/__init__.py", line 40, in async_get_device
    return (yield from self._get('/pods/{}'.format(uid),
  File "/usr/local/lib/python3.8/site-packages/pysensibo/__init__.py", line 90, in _get
    resp = yield from self._session.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 263, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 454, in async_device_update
    await self.async_update()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensibo/climate.py", line 399, in async_update
    self._do_update(data)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2020-08-29 12:13:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.bedroom fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensibo/climate.py", line 398, in async_update
    data = await self._client.async_get_device(self._id, _FETCH_FIELDS)
  File "/usr/local/lib/python3.8/site-packages/pysensibo/__init__.py", line 40, in async_get_device
    return (yield from self._get('/pods/{}'.format(uid),
  File "/usr/local/lib/python3.8/site-packages/pysensibo/__init__.py", line 90, in _get
    resp = yield from self._session.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 263, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 454, in async_device_update
    await self.async_update()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensibo/climate.py", line 399, in async_update
    self._do_update(data)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

## Additional context
I have tried the following already:
- With a fresh install of HA (still through promox)
- The beta versions of the shelly integration as well.
- Install manually (not through hacs)
- Using no discovery by specifying the devices through the config.yaml
  ![Image of Yaktocat](https://i.ibb.co/Mc0K8ym/ip.png)
- I have only one shelly 1 connected to my network through a static dhcp lease. (20 of them still boxed 😢 )
- Addons such as File Editor (Configurator) would fail to start sometimes.

**Comment by jwmaas** [comment]
I have recently installed two Shelly PM1's. Since then my HA server becomes unreachable within 24 hours and I need to restart it by pulling the power supply. Two nights in a row now.

**Comment by chemelli74** [comment]
@puttyman, you have a issue with pysensibo not with shelly.

@jwmaas, firmware 1.8 is supported from 0.2.0b1 and later.

Simone

**Comment by jwmaas** [comment]
Does this mean I should not have upgraded the firmware? Can I go back?

Or how can I install 0.2.0b1

Met groet, Jan Willem
+31 651 119 718

**Comment by puttyman** [comment]
@chemelli74 you could have asked to try without pysensibo before closing but anyway...

Its not an issue with neither shelly and pysensibo. My router is an Amplifi HD using hardware NAT. Turning it off resolved the issue. Would be interesting to know why. Perhaps could be a bug on the router side.
