### ISSUE TITLE
[BUG] Log filled with NoneType errors

### ISSUE THREAD

**Issue by DPH** [StyraHem/ShellyForHASS#402]
## Environment

- ShellyForHASS release with the issue: Current
- Last working ShellyForHASS release (if known): a few days ago
- Home Assistant Core release with the issue: [supervisor.homeassistant] Successful run Home Assistant 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv):  HASSIO -  Detect HassOS 4.12

## Describe the bug

 errors every second or so in log

## Steps to Reproduce

Just happens !

## Expected behavior

Not to error all the time and fill the log

## Traceback/Error logs

```Log:
2020-08-29 16:54:45 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method


2020-08-29 16:54:49 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 53, in update
    self.info_values[INFO_VALUE_SWITCH] = switch_state > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'```



```txt

```

**Comment by chemelli74** [comment]
Firmware 1.8 is supported by 0.2.0b1 or later.

Simone
