### ISSUE TITLE
Shelly 2.5 unavailable statue 

### ISSUE THREAD

**Issue by eliorerz** [StyraHem/ShellyForHASS#403]
Shelly 2.5 not working most of the time (95% of the time is on unavailable state) 

On the logs I'm seeing the following error:

`Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 50, in update
    self.info_values[INFO_VALUE_CURRENT_CONSUMPTION] = round(consumption)
TypeError: type NoneType doesn't define __round__ method`

Another error :
`
Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 53, in update
    self.info_values[INFO_VALUE_SWITCH] = switch_state > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'
`

Home Assistant version (docker) : 0.114.4
HACS Version: 1.5.2
Shelly integration version: 1.9

**Comment by chpego** [comment]
Which firmware of your Shelly 2.5 do you use? If 1.8 it's currently incompatible with version 1.9 of ShellyForHASS. A new version is in preparation

**Comment by azriele** [comment]
> Which firmware of your Shelly 2.5 do you use? If 1.8 it's currently incompatible with version 1.9 of ShellyForHASS. A new version is in preparation

Yes, I'm using 1.8.3
