### ISSUE TITLE
Shelly keeps turning on and off every minute 

### ISSUE THREAD

**Issue by SamMousa** [StyraHem/ShellyForHASS#419]
I'm not sure if it physically switches every minute or if it just changes state in hass. (not at home so unable to confirm) 

Log Details (ERROR)

Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/coap.py:191
First occurred: August 31, 2020, 9:29:55 PM (19791 occurrences)
Last logged: 8:24:30 AM

Error receive CoAPTraceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop self._root.update_block(device_id, device_type, File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block block.update(data, ipaddr) File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update dev.update(data) File "/usr/local/lib/python3.8/site-packages/pyShelly/switch.py", line 46, in update self._update(state > 0, {'last_event' : self.last_event, TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by SamMousa** [comment]
Possible duplicate of #413

**Comment by SamMousa** [comment]
Seems to be resolved in latest beta. Apologies
