### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zsbobbob** [StyraHem/ShellyForHASS#437]
## Environment

- ShellyForHASS release with the issue: 0.2.1 beta 1
- Last working ShellyForHASS release (if known): 0.1.9
- Home Assistant Core release with the issue: 0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): ubuntu 18.04/docker

## Traceback/Error logs

```txt

```

**Comment by miljume** [comment]
+1 I also experience this problem

**Comment by hakana** [comment]
Did you update the firmware also when got these errors?

**Comment by zsbobbob** [comment]
Yes, Shelly devices on 1.8.3 firmware

**Comment by miljume** [comment]
I have the same issue with 0.2.2 beta 1
Running 1.9.3 on my D/W sensors and 2021.1.4

**Comment by Henry-Sir** [comment]
I have the same issues:

## Environment

- ShellyForHASS release with the issue: 0.2.1
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: core-2021.2.3
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant OS 5.11 / supervisor-2021.02.6


## Error logs
Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py:69
First occurred: 13. Februar 2021, 16:18:27 (3250 occurrences)
Last logged: 11:37:09

Error receiving MQTT message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 59, in _loop
    shelly_type, device_id = shelly_id.rsplit('-',1)
ValueError: not enough values to unpack (expected 2, got 1)

Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py:69
First occurred: 13. Februar 2021, 16:22:38 (94 occurrences)
Last logged: 11:34:03

Error receiving MQTT message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 58, in _loop
    shelly_id = topics[1]
IndexError: list index out of range


Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py:69
First occurred: 13. Februar 2021, 16:54:18 (28 occurrences)
Last logged: 11:15:12

Error receiving MQTT message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 45, in _loop
    topic = data[2:2+topic_len].decode('ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 19: ordinal not in range(128)

Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py:69
First occurred: 13. Februar 2021, 21:37:54 (12 occurrences)
Last logged: 06:35:26

Error receiving MQTT message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 25, in _loop
    head = self._connection.recv(1)
ConnectionResetError: [Errno 104] Connection reset by peer
