### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Phatee** [StyraHem/ShellyForHASS#442]
## Environment

- ShellyForHASS release with the issue: 0.2.1 beta 1
- Last working ShellyForHASS release (if known): -
- Home Assistant Core release with the issue: 242
- Operating environment (Home Assistant/Supervised/Docker/venv): HassOS 4.13

## Traceback/Error logs

```txt

```

**Comment by miljume** [comment]
I have almost the same issue but in my case the traceback look like this

`Logger: homeassistant
Source: custom_components/shelly/__init__.py:194
First occurred: 19:05:47 (1 occurrences)
Last logged: 19:05:47

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/shelly/__init__.py", line 194, in start_up
    pys.start()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 130, in start
    self._mqtt.start()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 98, in start
    self._init_socket()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 104, in _init_socket
    sock.bind((self._root.bind_ip, self._root.mqtt_port))
OSError: [Errno 98] Address in use`

**Comment by hakana** [comment]
> I have almost the same issue but in my case the traceback look like this
> 
> ```
> Logger: homeassistant
> Source: custom_components/shelly/__init__.py:194
> First occurred: 19:05:47 (1 occurrences)
> Last logged: 19:05:47
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/shelly/__init__.py", line 194, in start_up
>     pys.start()
>   File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 130, in start
>     self._mqtt.start()
>   File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 98, in start
>     self._init_socket()
>   File "/usr/local/lib/python3.8/site-packages/pyShelly/mqtt.py", line 104, in _init_socket
>     sock.bind((self._root.bind_ip, self._root.mqtt_port))
> OSError: [Errno 98] Address in use
> ```

This is because you have set the MQTT_PORT to a port already used. Just use another port. This is not related to this issue.

**Comment by hakana** [comment]
This is because you have set HOST_IP to an invalid or not existing IP address.

HOST_IP must be set to an IP address existing on the HA computer. Run terminal in HA and see what IP address you have.
