### ISSUE TITLE
[BUG] issue in pyShelly ?

### ISSUE THREAD

**Issue by chpego** [StyraHem/ShellyForHASS#443]
## Environment

- ShellyForHASS release with the issue:  0.2.0
- Last working ShellyForHASS release (if known): 0.1.9
- Home Assistant Core release with the issue:  0.114.4
- Operating environment (Home Assistant/Supervised/Docker/venv): HA

## Traceback/Error logs

```txt
Logger: pyShelly
Source: /usr/local/lib/python3.8/site-packages/pyShelly/utils.py:38
First occurred: 17:14:15 (1 occurrences)
Last logged: 17:14:15

 Error http GET: http://https://repo.shelly.cloud/files/firmware, <urlopen error [Errno -3] Try again>, Traceback (most recent call last): File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open h.request(req.get_method(), req.selector, req.data, headers, File "/usr/local/lib/python3.8/http/client.py", line 1240, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.8/http/client.py", line 1006, in _send_output self.send(msg) File "/usr/local/lib/python3.8/http/client.py", line 946, in send self.connect() File "/usr/local/lib/python3.8/http/client.py", line 1402, in connect super().connect() File "/usr/local/lib/python3.8/http/client.py", line 917, in connect self.sock = self._create_connection( File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -3] Try again During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/firmware.py", line 29, in _http_get f = urllib.request.urlopen(url) File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open response = self._open(req, data) File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open result = self._call_chain(self.handle_open, protocol, protocol + File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/usr/local/lib/python3.8/urllib/request.py", line 1393, in https_open return self.do_open(http.client.HTTPSConnection, req, File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open raise URLError(err) urllib.error.URLError: <urlopen error [Errno -3] Try again> 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 1402, in connect
    super().connect()
  File "/usr/local/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
```

**Comment by Octofinger** [comment]
The URL getting latest firmwares is incorrect.
**http://https://**repo.shelly.cloud/files/firmware

**Comment by hakana** [comment]
Just look like it could not access the firmware archive. Does this give you any problems?

The http://https.// is just an error in logging and will be fixed in next release.

**Comment by chpego** [comment]
OK, thks for information, cool 👍
