### ISSUE TITLE
[BUG] Error: Handling request

### ISSUE THREAD

**Issue by Bodge-IT** [StyraHem/ShellyForHASS#445]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): 0.2.0
- Home Assistant Core release with the issue: 0.115.0b9
- Operating environment (Home Assistant/Supervised/Docker/venv): supervised

## Describe the bug

When trying to configure the S4H in the integrations panel, the popup shows that its being installed but sits there and never finishes.  With debug active, I get the following error:
```
Log Details (ERROR)
Logger: aiohttp.server
Source: custom_components/shelly/config_flow.py:44
First occurred: 11:32:59 (1 occurrences)
Last logged: 11:32:59
```

## Steps to Reproduce

Install via HACS or manually, same result.  Uninstall, reinstall no fix.

## Expected behavior

Popup should close after install tasks finish and config form should become available

## Screenshots

![Image-202009-005](https://user-images.githubusercontent.com/1881642/93201021-7fad6f00-f748-11ea-84a4-de49a0228aca.jpg)

## Traceback/Error logs

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 160, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 204, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/shelly/config_flow.py", line 44, in async_step_input
    title=user_input["id_prefix"],
TypeError: 'NoneType' object is not subscriptable

```

## Additional context

Possibly self-inflicted, I had tried the new built-in Shelly too before realising that it was a little lite for my needs.  I uninstalled that restart and then issues startedsometime after that.  Before then I had actually updated to 0.2.0 which had fixed my CoAP warnings and fixed all the latency and associated issues with dimmers etc.

**Comment by Bodge-IT** [comment]
OK, I managed to fix my install by manually adding the prefix (mentioned on line 44 in config_flow.py) and cloud server and token.
Strongly suspect this mot a bug but an issue with the interaction of the two Shelly integrations now available.

I may not be the only one tripping up here tho.

**Comment by GR3ee3N** [comment]
Hi, I have exact the same issue.
I am on a fresh 0.115.4 installation and I did not mess with the new build in integration.

**Comment by Bodge-IT** [comment]
Are you able to fix with the info provided or need some additional support?

**Comment by GR3ee3N** [comment]
Yes, I also tried to edit config_flow.py on line 44 as you did. With the edit done, setting up the integration worked but I immediately ran into the next error. HA didn't like something about the config idk. I can share the logs later, I don't have access to them right now.

Maybe I did something wrong. Do you mind sharing your changes to the integration that made it work?

**Comment by Bodge-IT** [comment]
In addition to config_flow.py change, I add the manual config to the configuration.yaml file:
```shelly:
  cloud_auth_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  cloud_server: "shelly-XXXXX.shelly.cloud"```

**Comment by GR3ee3N** [comment]
I see, I did not do that. Not adding the manual config would also make sense with the error that I got. I'll try that later, thanks for your help!

Besides that, this seems to be a reproducible issue. What do you think about re-opening it?

**Comment by Bodge-IT** [comment]
Happy to re-open, just don't know how to recreate the problem.  Did it happen after an update for you?

**Comment by GR3ee3N** [comment]
No, it happend on a completely fresh 0.115.4 docker installation.
I directly tried to set up hacs and then ShellForHASS without any other configuration before that.
Updating from my production instance would probably work fine since the integration is already configured via yaml.

**Comment by Bodge-IT** [comment]
OK, the devs can have a look...plenty of info here.

**Comment by mozzhead164** [comment]
Any more feedback on the issue? Also facing the same problem

**Comment by hakana** [comment]
Did you restart HA after installing ShellyForHass from HACS. Look like it trying to add the new build in Shelly integration on the picture.

**Comment by Bodge-IT** [comment]
@hakana When I took that SS, the system had been turned on/off several times following updates etc.  Until I fixed my install, I had no access to ShellyForHacs for almost a week or so.

**Comment by Batgodfr** [comment]
Hi, i have the same issue, but i can't find what to replace!
Any help will be nice
Thanks

**Comment by Bodge-IT** [comment]
Just try adding:
`
shelly:
  cloud_auth_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  cloud_server: "shelly-XXXXX.shelly.cloud"
`
with your replaced version to the configurastion.yaml

**Comment by Batgodfr** [comment]
Hello Bodge,

I tried and i modified config_flow.py 
               title="shelly",
And it worked!
Thank you Bodge, have a great day ;)

**Comment by hakana** [comment]
I have added some code that hopefully takes care of this.

**Comment by koldogut** [comment]
Still have the same issue in 0.2.1 after install/deinstall the component several times; title="shelly" solution removed the error but integration keeps configuring with this new entries in the logs:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 160, in get
return await super().get(request, flow_id)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in get
result = await self._flow_mgr.async_configure(flow_id)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 235, in _async_handle_step
result = await self.async_finish_flow(flow, dict(result))
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 493, in async_finish_flow
entry = ConfigEntry(
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 154, in __init__
self.data = MappingProxyType(data)
TypeError: mappingproxy() argument must be a mapping, not NoneType
```

**Comment by metalmini** [comment]
When will this fix be available? Currently its blocking me from using the module :-(
