### ISSUE TITLE
[BUG] Shelly hub not reachable - SSL certificate not recognized

### ISSUE THREAD

**Issue by wsw70** [StyraHem/ShellyForHASS#492]
## Environment

- ShellyForHASS release with the issue: 0.2.1
- Last working ShellyForHASS release (if known): the previous one if I am not mistaken
- Home Assistant Core release with the issue: 0.118.4
- Operating environment (Home Assistant/Supervised/Docker/venv): docker `:latest` container on an Ubuntu 18.04 host

## Describe the bug

The firmware check for the shelly component fails when accessing https://repo.shelly.cloud/files/firmware because of a failed certificate check by `requests`

## Steps to Reproduce

N/A (other than installing the integration)

## Expected behavior

No errors when connecting to https://repo.shelly.cloud/files/firmware

## Traceback/Error logs

```txt
2020-12-01 18:05:46 ERROR (FirmwareManage) [pyShelly] Error http GET: https://repo.shelly.cloud/files/firmware, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)>, Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/firmware.py", line 29, in _http_get
    f = urllib.request.urlopen(url)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)>
```

## Additional context

Making a `requests` call from a python prompt within the container yields the same error.

A solution to the problem would be not to check the validity of the certificate, which is not useful anyway.

**Comment by hakana** [comment]
Do you have working code or can do a PR?

**Comment by wsw70** [comment]
Well, after several experimentations (going back to the native integration, and then again to ShellyForHASS - the story is at https://community.home-assistant.io/t/how-exactly-are-shelly-integrations-related/251270) I do not see the issue anymore.

I am closing it for now, sorry for the disturbance - I was quite (and still am) surprised that integrations replace each other, thus my misunderstanding of the whole situation.

**Comment by wsw70** [comment]
> I saw Shelly have some problem with the certificates on some servers last days, maybe related to that.

You are right. I saw the issue again today and I see that they again renewed their certificate today - there must have been some issues with the dates before
