### ISSUE TITLE
[BUG] Shelly flood sensor stays on.

### ISSUE THREAD

**Issue by miamilabs** [StyraHem/ShellyForHASS#503]
## Environment

- ShellyForHASS release with the issue:  Release 0.2.1 (Manual Install)
- Last working ShellyForHASS release (if known): 2020.12.1
- Home Assistant Core release with the issue: 2020.12.1
- Operating environment (Home Assistant/Supervised/Docker/venv):  Home Assistant/Supervised/MQTT Broker
- Shelly Flood version 20201128-102432/v1.9.2@e83f7025

## Describe the bug
After "Shelly Flood" report of flood, the sensor stays "on".

## Steps to Reproduce
Shelly Flood, trigger alert.

## Expected behavior
The sensor should return to "off" state after certain of time. This not happen provably as the shelly flood is turning off after it reported that flood happened.

## Screenshots
<img width="395" alt="Screenshot 2020-12-23 at 22 30 00" src="https://user-images.githubusercontent.com/8977700/103100500-1d032380-4613-11eb-98fa-174e2976f663.png">

## Traceback/Error logs
`2020-12-24 19:11:08 ERROR (Poll status) [pyShelly] Error update device status: B085CA SHWT-1, , Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 191, in update_status_information
    dev.raise_updated(force_update_devices)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 59, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state
    assert self.hass is not None
AssertionError
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 191, in update_status_information
    dev.raise_updated(force_update_devices)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 59, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state
    assert self.hass is not None
AssertionError
`

**Comment by hakana** [comment]
Duplicate #504
