### ISSUE TITLE
[BUG] Shelly1 works after few hours, then HA can't toggle/switch the shelly

### ISSUE THREAD

**Issue by lebherz** [StyraHem/ShellyForHASS#509]
## Environment

- ShellyForHASS release with the issue:  0.2.2 beta1 AND 0.2.1
- Last working ShellyForHASS release (if known): I don't now
- Home Assistant Core release with the issue: Home Assistant 2020.12.2
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant OS 5.9
- Shelly Version: 20201228-092119/v1.9.3@ad2bb4e3

## Describe the bug

Shelly1 works after few hours, then HA can't toggle/switch the shelly

## Steps to Reproduce

see above

## Expected behavior

switching the switch at any time :)

## Traceback/Error logs

```txt


Logger: pyShelly
Source: helpers/entity.py:422
First occurred: December 31, 2020, 5:35:13 PM (21356 occurrences)
Last logged: 12:54:39 AM

    Error update device status: 9425E5 SHSW-1, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 197, in update_status_information dev.raise_updated(force_update_devices) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated callback(self) File "/config/custom_components/shelly/device.py", line 59, in _updated self._update_ha_state() File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state assert self.hass is not None AssertionError
    Error update device status: 68C63AFACA63 SHEM-3, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 197, in update_status_information dev.raise_updated(force_update_devices) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated callback(self) File "/config/custom_components/shelly/device.py", line 59, in _updated self._update_ha_state() File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state assert self.hass is not None AssertionError
    Error update device status: 68C63AFACA63-1 SHEM-3, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 197, in update_status_information dev.raise_updated(force_update_devices) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated callback(self) File "/config/custom_components/shelly/device.py", line 59, in _updated self._update_ha_state() File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state assert self.hass is not None AssertionError
    Error update device status: 68C63AFACA63-2 SHEM-3, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 197, in update_status_information dev.raise_updated(force_update_devices) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated callback(self) File "/config/custom_components/shelly/device.py", line 59, in _updated self._update_ha_state() File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state assert self.hass is not None AssertionError
    Error update device status: 68C63AFACA63-3 SHEM-3, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 197, in update_status_information dev.raise_updated(force_update_devices) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated callback(self) File "/config/custom_components/shelly/device.py", line 59, in _updated self._update_ha_state() File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state assert self.hass is not None AssertionError

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 281, in update_block
    block.update_coap(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 93, in update_coap
    dev.raise_updated()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 36, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 59, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state
    assert self.hass is not None
AssertionError


```

**Comment by hakana** [comment]
The log is not related to the problem you describe.

Is this still an issue?

**Comment by lebherz** [comment]
the error in the log disappears
