### ISSUE TITLE
Error receive CoAP

### ISSUE THREAD

**Issue by tkerstan** [StyraHem/ShellyForHASS#513]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known): Unknown
- Home Assistant Core release with the issue: 2021.1.1
- Operating environment (Home Assistant/Supervised/Docker/venv):  Docker

## Describe the bug
Error Message when CoAP message is received

## Steps to Reproduce
Shelly Firmware is 1.9.3

## Expected behavior
No error messages, as these errors spam my log....

## Traceback/Error logs
```2021-01-11 17:26:30 DEBUG (CoAP) [pyShelly] CoAP msg: 192.168.4.16 b'P\x1e\xa6\xb6\xb3cit\x01s\xed\x0b\xec\x08SHSW-1#BCDDC27742B6#2\xd2C\x96\x00\x82\x80\x00\xff{"G":[[0,9103,0],[0,1101,1],[0,2101,0],[0,2102,""],[0,2103,0]]}'
2021-01-11 17:26:30 DEBUG (CoAP) [pyShelly] CoAP msg: 30 192.168.4.16 bytearray(b'P\x1e\xa6\xb6\xb3cit\x01s\xed\x0b\xec\x08SHSW-1#BCDDC27742B6#2\xd2C\x96\x00\x82\x80\x00\xff{"G":[[0,9103,0],[0,1101,1],[0,2101,0],[0,2102,""],[0,2103,0]]}')
2021-01-11 17:26:30 DEBUG (CoAP) [pyShelly] CoAP Code: 30, Type SHSW-1, Id BCDDC27742B6, Payload *{"G":[[0,9103,0],[0,1101,1],[0,2101,0],[0,2102,""],[0,2103,0]]}*
2021-01-11 17:26:30 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 182, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 242, in update_block
    block.update(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 92, in update
    dev.update(data)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/relay.py", line 53, in update
    self.info_values[INFO_VALUE_SWITCH] = switch_state > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

## Additional context
Integration seems to work fine beside of this message. Not clear if there is any effect, because I am currently starting with CoAP as protocol to improve timing behavior.

**Comment by tkerstan** [comment]
Did not notice newer version. No issue in 0.2.1
