### ISSUE TITLE
[ERROR] can not connect

### ISSUE THREAD

**Issue by lecrams** [StyraHem/ShellyForHASS#548]
Hi,

I added in my configuration the following lines to get connected to the cloud.

shelly:
  cloud_auth_key: !secret auth_key
  cloud_server: https://shelly-23-eu.shelly.cloud
  discovery: true  #add all devices (default)
  sensors:
    - all #show all sensors

Despite this I get an connection error (below) when (re)starting? 
Do I also need to enter a username and passwd or is the auth_key sufficient?

2021-04-15 14:08:16 WARNING (Cloud) [pyShelly] Error connect cloud, [Errno -2] Name does not resolve
2021-04-15 14:08:18 WARNING (Cloud) [pyShelly] Error connect cloud, [Errno -2] Name does not resolve
2021-04-15 14:08:23 ERROR (CoAP) [pyShelly] Error receive CoAP Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 187, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 307, in update_block
    block.update_coap(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 101, in update_coap
    dev.raise_updated()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 45, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 58, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
Tyr to remove https:// from cloud_server and I think it will work better

**Comment by lecrams** [comment]
That removed the cloud connect error but still I get an other error:

AttributeError: 'NoneType' object has no attribute 'add_job'
2021-04-15 15:24:06 ERROR (CoAP) [pyShelly] Error receive CoAP
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 187, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 307, in update_block
    block.update_coap(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 101, in update_coap
    dev.raise_updated()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 45, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/device.py", line 58, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/device.py", line 51, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 440, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore

**Comment by Extreme79** [comment]
I'm running into the same issue.
Suggestions?

**Comment by hakana** [comment]
This error usually is a result of an earlier error, have a look in the log for the first error to see the cause of this.
