### ISSUE TITLE
[BUG]Error receiving CoAP UDP

### ISSUE THREAD

**Issue by vdiogo** [StyraHem/ShellyForHASS#558]
## Environment

- ShellyForHASS release with the issue: 0.2.3.beta.2
- Last working ShellyForHASS release (if known): N/A
- Home Assistant Core release with the issue: core-2021.3.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant Supervised

## Describe the bug

Getting an error in the Log and can't understand 

## Steps to Reproduce

No specific action done

## Expected behavior

Not to have the error

## Traceback/Error logs

Logger: pyShelly
Source: helpers/entity.py:421 
First occurred: 29 de abril de 2021 23:24:43 (132779 occurrences) 
Last logged: 11:01:00

Error receiving CoAP UDP, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 187, in _loop self._root.update_block(device_id, device_type, File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 307, in update_block block.update_coap(data, ipaddr) File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 111, in update_coap self.raise_updated() File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 45, in raise_updated callback(self) File "/config/custom_components/shelly/block.py", line 68, in _updated self._update_ha_state() File "/config/custom_components/shelly/block.py", line 60, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 421, in schedule_update_ha_state assert self.hass is not None AssertionError
Error update loop, , Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 334, in _update_loop block.check_available() File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 168, in check_available self.raise_updated(True) File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 45, in raise_updated callback(self) File "/config/custom_components/shelly/block.py", line 68, in _updated self._update_ha_state() File "/config/custom_components/shelly/block.py", line 60, in _update_ha_state self.schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 421, in schedule_update_ha_state assert self.hass is not None AssertionError
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/coap.py", line 187, in _loop
    self._root.update_block(device_id, device_type,
  File "/usr/local/lib/python3.8/site-packages/pyShelly/__init__.py", line 307, in update_block
    block.update_coap(data, ipaddr)
  File "/usr/local/lib/python3.8/site-packages/pyShelly/block.py", line 111, in update_coap
    self.raise_updated()
  File "/usr/local/lib/python3.8/site-packages/pyShelly/base.py", line 45, in raise_updated
    callback(self)
  File "/config/custom_components/shelly/block.py", line 68, in _updated
    self._update_ha_state()
  File "/config/custom_components/shelly/block.py", line 60, in _update_ha_state
    self.schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 421, in schedule_update_ha_state
    assert self.hass is not None
AssertionError

```

## Additional context
<!--
  Add any other context about the problem here.
-->

**Comment by apeeters** [comment]
I see the same stacktrace on 0.2.2.
