### ISSUE TITLE
[BUG] Config flow could not be loaded

### ISSUE THREAD

**Issue by jasonmadigan** [StyraHem/ShellyForHASS#562]
## Environment

- ShellyForHASS release with the issue: 0.22.x (latest, just installed)
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: Latest
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Describe the bug
Installed via HACs, restarted. Showing a new "Discovered" integration for Shelly smart home. When "Configure" is clicked, I get an error: `Config flow could not be loaded`

## Screenshots

<img width="588" alt="Screenshot 2021-05-24 at 10 40 07" src="https://user-images.githubusercontent.com/4467/119328876-7d5ac780-bc7c-11eb-8be9-c158908e5903.png">

## Traceback/Error logs

```txt

```

**Comment by nickelnine** [comment]
Same here. Running 0.2.2 on Home Assistant Container 2021.6.4

**Comment by hubikj** [comment]
Same here. Running latest versions: 0.2.2 ShellyForHASS on Home Assistant OS 6.0 with Core version core-2021.6.5 and Supervisor supervisor-2021.06.3

**Comment by psilantropy** [comment]
Same issue here. I did have the standard integration loaded and removed it. Now via HACS.

**Comment by Caroga** [comment]
Same here, got the following log lines though:

```
homeassistant_1  | 2021-08-17 22:39:47 ERROR (MainThread) [aiohttp.server] Error handling request
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
homeassistant_1  |     resp = await self._request_handler(request)
homeassistant_1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
homeassistant_1  |     resp = await handler(request)
homeassistant_1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
homeassistant_1  |     return await handler(request)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
homeassistant_1  |     return await handler(request)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 84, in forwarded_middleware
homeassistant_1  |     return await handler(request)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
homeassistant_1  |     return await handler(request)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
homeassistant_1  |     return await handler(request)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
homeassistant_1  |     return await handler(request)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
homeassistant_1  |     result = await result
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 146, in get
homeassistant_1  |     return await super().get(request, flow_id)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 95, in get
homeassistant_1  |     result = await self._flow_mgr.async_configure(flow_id)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
homeassistant_1  |     result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 295, in _async_handle_step
homeassistant_1  |     result = await self.async_finish_flow(flow, result.copy())
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 661, in async_finish_flow
homeassistant_1  |     entry = ConfigEntry(
homeassistant_1  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 194, in __init__
homeassistant_1  |     self.data = MappingProxyType(data)
homeassistant_1  | TypeError: mappingproxy() argument must be a mapping, not NoneType
```

Hope this helps with anything. :)

**Comment by Caroga** [comment]
Update: manually enabling the integration works.

**Comment by psilantropy** [comment]
I found that if I install the standard Home Assistant integration first, then the HACS integration I get the HACs one inside the HA integration and it works - but breaks all the devices that HA discovered.

**Comment by sabixx** [comment]
same error, I got a workaround by adding: 

shelly: 

to my configuration.yaml file. (I'm new to home-assistant, it might be working entirely different at the moment).
