### ISSUE TITLE
[BUG] Unable to change settings flag

### ISSUE THREAD

**Issue by enricozocca** [StyraHem/ShellyForHASS#627]
## Environment

- ShellyForHASS release with the issue: latest
- Last working ShellyForHASS release (if known): none
- Home Assistant Core release with the issue: 2012.12.0
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Traceback/Error logs

```txt

```

**Comment by hakana** [comment]
Need more info about the problem...

**Comment by enricozocca** [comment]
Yes sorry, I don't know why but text was lost.

This is the problem: I'm not be able to change checkbox flag on Settings page (new Sidebar), for example if I want to create battery sensor. Flag not change when i click. nothing happen. Config page works well

This is the log:
2021-12-15 22:49:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140043729705664] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/shelly/ws_handler.py", line 114, in shelly_setting
    instance.set_config_sensor(id, value=="True")
  File "/config/custom_components/shelly/__init__.py", line 192, in set_config_sensor
    self.update_config_list(CONF_SENSORS, id, value)
  File "/config/custom_components/shelly/__init__.py", line 222, in update_config_list
    list = options[type] = options[type].copy()
KeyError: 'sensors'

Regards
Enrico

**Comment by hakana** [comment]
Can you take a screening show on the settings page?

Do you have Shelly config in yaml file or added in HA gui?

**Comment by enricozocca** [comment]
Here below settings page. I'm able to change value on textbox and it's working (example decimals field). 
Not possible to tick/untick checbox.  

<img width="1466" alt="immagine" src="https://user-images.githubusercontent.com/7684081/146355277-14a79027-ddec-4272-a0eb-b963cf2ec57a.png">

**Comment by hakana** [comment]
I have found the problem and it will be fixed in the next release, hopefully, released today.

workaround: If you go to configuration for the integration in HA GUI and select sensors there it will then be possible to use Shelly GUI settings.

**Comment by enricozocca** [comment]
Workaround it's working but probably due to a limitiation is not possible to go on 2nd page without put mttq settings. This  probably creste in my HA installation an issue and after restart shelly light entity was not discovered anymore. 
I think it's better to way next release!
Enrico
