### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cippo2019** [StyraHem/ShellyForHASS#630]
Environment
ShellyForHASS release with the issue: 0.3.2 (never seen with the previous version)
Last working ShellyForHASS release (if known): 0.3.1
Home Assistant Core release with the issue: core-2021.11.5
Operating environment: HA over OVA
Describe the bug:
after last update to 0.3.2 after some time  i get this error and disappear after HA restart (11.5)

2021-12-16 15:34:36 ERROR (Update loop) [pyShelly] Error update loop, 'NoneType' object has no attribute 'addresses', Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 374, in _update_loop
    self.check_by_ip()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 241, in check_by_ip
    ip_addr = self._mdns.get_ip(*data['id'].split('|'))
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mdns.py", line 20, in get_ip
    for addr in info.addresses:
AttributeError: 'NoneType' object has no attribute 'addresses'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 374, in _update_loop
    self.check_by_ip()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 241, in check_by_ip
    ip_addr = self._mdns.get_ip(*data['id'].split('|'))
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mdns.py", line 20, in get_ip
    for addr in info.addresses:
AttributeError: 'NoneType' object has no attribute 'addresses'

Steps to Reproduce
waiting some time

Expected behavior

Screenshots

Additional context

thanks a lot

Tiziano

**Comment by Cippo2019** [comment]
Hi Hakana
thanks for FIXED :-)

do you know more or less when 0.3.3 will be released ? 

wbr
Tiziano

**Comment by hakana** [comment]
Now 😉


Från: Cippo2019 ***@***.***>
Skickat: den 16 december 2021 22:39
Till: StyraHem/ShellyForHASS ***@***.***>
Kopia: Håkan Åkerberg ***@***.***>; Assign ***@***.***>
Ämne: Re: [StyraHem/ShellyForHASS] [BUG] (Issue #630)


Hi Hakana
thanks for FIXED :-)

do you know more or less when 0.3.3 will be released ?

wbr
Tiziano

**Comment by Cippo2019** [comment]
hahah
ok 
to fast :-)
thanks a lot for your effort !

**Comment by hakana** [comment]
Hi,

Ok, I will do it in slow motion next time 😉


Från: Cippo2019 ***@***.***>
Skickat: den 16 december 2021 22:43
Till: StyraHem/ShellyForHASS ***@***.***>
Kopia: Håkan Åkerberg ***@***.***>; Assign ***@***.***>
Ämne: Re: [StyraHem/ShellyForHASS] [BUG] (Issue #630)


hahah
ok
too fast :-)
thanks a lot for your effort !

**Comment by Cippo2019** [comment]
sorry for late in this close ! it works perfectly (sorry again)
