### ISSUE TITLE
New discovered device: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by fvant** [StyraHem/ShellyForHASS#652]
New device (my only shelly) was auto discovered, clicking Configure gives this error:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

HAOS 7.4
Core 2022.2.8

**Comment by robr92** [comment]
same by me

**Comment by JohanLander** [comment]
yes i have this too ...

**Comment by PhillipRt** [comment]
Seems to be related to this error message for me:
```
ERROR: Cannot install paho-mqtt==1.5.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts 
```

**Comment by thundergreen** [comment]
same as: https://github.com/StyraHem/ShellyForHASS/issues/655

**Comment by Ascariota** [comment]
SAme issue

**Comment by PhillipRt** [comment]
Fixed by #658 for me

**Comment by fvant** [comment]
i updated to 0.3.5 this morning, rebooted but get the same error. I have
not tried removing and install it fresh

**Comment by andrebbruno** [comment]
After upgrading to 2022.3.1 it stopped working again:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/shelly/__init__.py:330
Integration: Shelly smart home (documentation)
First occurred: 10:44:51 PM (1 occurrences)
Last logged: 10:44:51 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/shelly/__init__.py", line 330, in start_up
    pys.start()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 185, in start
    self._mqtt_server.start()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 123, in start
    self._init_socket()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 129, in _init_socket
    sock.bind((self._root.bind_ip, self._root.mqtt_port))
OSError: [Errno 98] Address in use

**Comment by tsparber** [comment]
I am new to ShellyForHASS and thus tried to install it the first time on Home Assistant 2022.3.5.
My devices are auto discovered, but cannot be set up as an error  500 Internal Server Error Server got itself in trouble is shown in the configuration screen.

ShellyForHASS v0.3.5 via HACS.

Error Log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 97, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 360, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 708, in async_finish_flow
    entry = ConfigEntry(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 220, in __init__
    self.data = MappingProxyType(data)
TypeError: mappingproxy() argument must be a mapping, not NoneType
```

**Comment by hakana** [comment]
Have you restarted HA after installation of ShellyForHass?

**Comment by tsparber** [comment]
Yes i did a restart of HA as suggested by HACS.

I did a another search regarding the stack trace and found the similar issues #496 and #562.

Manually adding a new instance of the integration works as suggested in https://github.com/StyraHem/ShellyForHASS/issues/496#issuecomment-745570525
Search for Shelly integration and create a new instance, after a restart the auto discovered instance is removed.
