### ISSUE TITLE
[BUG] Invalid entity ID since Home Assistant 2022.03.0

### ISSUE THREAD

**Issue by JurajNyiri** [StyraHem/ShellyForHASS#659]
# Update

Fix is available inside PR https://github.com/StyraHem/ShellyForHASS/pull/660 .

## Environment

- ShellyForHASS release with the issue: 0.3.3 with https://github.com/StyraHem/ShellyForHASS/pull/658
- Last working ShellyForHASS release (if known): N/A
- Home Assistant Core release with the issue: 2022.03.0
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised

## Describe the bug

Installed Home Assistant 2022.03.0, applied https://github.com/StyraHem/ShellyForHASS/pull/658 to fix https://github.com/StyraHem/ShellyForHASS/issues/655 . Restarted, now most of the entities are not working.

Total consumption and firmware switch entities are working, current consumption entities are not.

## Steps to Reproduce

1. Install Home Assistant 2022.03.0
2. Apply https://github.com/StyraHem/ShellyForHASS/pull/658 to the latest ShellyForHass version 0.3.3
3. Restart Hass

## Expected behavior
Current consumption and other entities should be working.

## Screenshots

![image](https://user-images.githubusercontent.com/5785999/156470767-78acfc8d-dd76-4b98-998f-01c02183974a.png)

## Traceback/Error logs

```txt
2022-03-03 00:53:02 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_1_current_consumption
2022-03-03 00:53:05 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_2_current_consumption
2022-03-03 00:53:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_1_current_consumption
2022-03-03 00:53:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_2_current_consumption
2022-03-03 00:53:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_3_current_consumption
2022-03-03 00:53:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_1_current_consumption
2022-03-03 00:53:07 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_2_current_consumption
2022-03-03 00:53:07 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_3_c45bbe604121_3_current_consumption
2022-03-03 00:53:07 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_b0858a_1_current_consumption
2022-03-03 00:53:09 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_b0858a_2_current_consumption
2022-03-03 00:53:09 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_b0858a_2_current_consumption
2022-03-03 00:53:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 638, in _async_write_ha_state
    attr.update(self.hass.data[DATA_CUSTOMIZE].get(self.entity_id))
  File "/usr/src/homeassistant/homeassistant/helpers/entity_values.py", line 40, in get
    domain, _ = split_entity_id(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 148, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID .shelly_shem_b0858a_1_current_consumption
```

**Comment by JurajNyiri** [comment]
I have rolled back to Home Assistant 2022.02.9 using command `ha core update --version 2022.2.9`. I have left the integration code exactly like described above (so 0.3.3 with https://github.com/StyraHem/ShellyForHASS/pull/658 and everything works again. 

So there must be something new in 2022.03.0 breaking the entity IDs.

**Comment by blubbel42** [comment]
Same here. Interesting though: Before this my total consumption sensors were broken a I couldn't figure out why in any way. After upgrading and then rolling back because of issues now everything works fine as it never has before. My thought while looking at the error messages was that the prefixes (Sensor, switch...) of the entities were missing. But I am not sure how to interprete this here.
Greetings
Blubbel

**Comment by poldim** [comment]
I think it’s this based on the errors: https://www.home-assistant.io/blog/2022/03/02/release-20223/#updates-for-custom-integration-developers

> Helper: split_entity_id()
split_entity_id will now raise a ValueError if the passed value does not follow the basic entity ID format (<domain>.<object id>).
> 
> Previously it could return a list with a single item.
> 
> ([@balloob](https://github.com/balloob) - [#66835](https://github.com/home-assistant/core/pull/66835))

**Comment by mleiber** [comment]
Another observation. I got the shelly integration running by applying #658 (which wasn't that easy as I first had to remove the integration, delete and reinstall via HACS and then reconfigure the integration - otherwise I couldn't get HA to restart as it was complaining about that version conflict).

Now I have two Shelly integrations shown in the configuration:

![image](https://user-images.githubusercontent.com/52375201/156524771-b42f63a2-716b-4f4e-b3f3-6523f1b495a5.png)

I'm using yaml based configuration. The first one is for that, the second one looks like a UI based integration. Digging deeper, the first one lists 17 devices and 42 entities:

![image](https://user-images.githubusercontent.com/52375201/156525055-00e7a0a0-ed89-4c35-9857-f46f3e2f07c4.png)
 
The second one 17 devices (the same) and 11 entities. 

![image](https://user-images.githubusercontent.com/52375201/156525300-01e5abd5-1d63-472c-82d9-57f1480191d2.png)

The 11 entities of integration #2 seem to be all the binary_sensors that are missing from #1 above. 

One more detail that may be related is I have chosen no prefix ``id_prefix: "" # no prefix`` for the entities. This worked fine up until now.

**Comment by robr92** [comment]
same problem! I changed on manifest from 1.5.1 to 1.6.1 but when I check the configuration it gives me this error "Integration error: shelly - Requirements for shelly not found: ['paho-mqtt == 1.5.1']."

**Comment by matteos1** [comment]
same here

**Comment by JurajNyiri** [comment]
I am working on a fix, ETA 1 hour.

**Comment by JurajNyiri** [comment]
Fix available in PR https://github.com/StyraHem/ShellyForHASS/issues/659 .

**Comment by mleiber** [comment]
I will test it in half an hour. Thx for the quick fix!

Juraj Nyíri ***@***.***> schrieb am Do., 3. März 2022, 12:31:

**Comment by mleiber** [comment]
I did integrate your changes manually and it looks like it is working now. Needed a bit of cleanup to eliminate the orphan entities and 2nd integration that had been created by the defective version. Everything seems to be working fine now.

Thanks a lot for the quick remedy - now we have heating again in our living room. I've implemented a thermostat using a shelly switch which wasn't working anymore. Makes me think if I should make that dependent on the home automation ... ;-). 

anyway, thanks again!

**Comment by asiersan** [comment]
> Fix available in PR #660 .

Si we must wait for a new release?

**Comment by JurajNyiri** [comment]
@asiersan yes, or you apply the changes manually by following manual installation in https://github.com/JurajNyiri/ShellyForHASS/tree/fix_659 .

**Comment by belmont** [comment]
issue not fixed at all, just did update, shelly failed, did a rollback
