### ISSUE TITLE
[BUG] Shelly 2.5 and Shelly RGBW only show sensor, switches and light are unavailable

### ISSUE THREAD

**Issue by Stephan1908** [StyraHem/ShellyForHASS#666]
## Environment

- ShellyForHASS release with the issue: 0.3.5
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 2022.3.5
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Describe the bug

  Shelly 2.5 and Shelly RGBW only show sensor, switches and light are unavailable

## Screenshots
 
  
![grafik](https://user-images.githubusercontent.com/60405276/159549523-8ad814f1-16c5-409d-80f1-fd1182901efa.png)

## Traceback/Error logs
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/shelly/__init__.py:330
Integration: Shelly smart home (documentation)
First occurred: 19:05:04 (1 occurrences)
Last logged: 19:05:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/shelly/__init__.py", line 330, in start_up
    pys.start()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/__init__.py", line 185, in start
    self._mqtt_server.start()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 123, in start
    self._init_socket()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 129, in _init_socket
    sock.bind((self._root.bind_ip, self._root.mqtt_port))
OSError: [Errno 98] Address in use

```txt

```

**Comment by legi1** [comment]
I've the same issue any news on that?

**Comment by albertgaes** [comment]
I'm facing the same issue with an RGBW2.
The Shelly 1 is working fine.

**Comment by jhanson999** [comment]
I'm having the same problem.

**Comment by kaar372** [comment]
I have same problem with RGBW2

**Comment by krdslv** [comment]
i'm also having the same issue
If the light switch is off, says lights not found, physical switch on, lights detected but no controls.

![CaptureShelly](https://user-images.githubusercontent.com/69357951/172203025-995c6025-5385-404a-b381-ef3e677622c8.PNG)
