### ISSUE TITLE
[BUG] Can't configure under HA Core 2022.6.1

### ISSUE THREAD

**Issue by Masterz69** [StyraHem/ShellyForHASS#681]
## Environment

- ShellyForHASS release with the issue:  1.0.0.beta.2
- Last working ShellyForHASS release (if known): n/a
- Home Assistant Core release with the issue: 2022.6.1
- Operating environment (Home Assistant/Supervised/Docker/venv): HAOS

## Describe the bug
After HACS integration and HA integration added - opening config page http://ha.local:8123/shelly/config lasts forever....

## Steps to Reproduce
HACS Integrations - install ShellyforHASS
HA Integrations - install shelly integration
Press Configure

## Screenshots
![image](https://user-images.githubusercontent.com/15225823/171991712-d793a1df-a3e4-4358-9ae2-3110ee629a51.png)
^^ forever

## Traceback/Error logs
```txt
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 11:23:46 (2 occurrences)
Last logged: 11:27:19

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alarmo using this method at custom_components/alarmo/__init__.py, line 58: device_registry = await dr.async_get_registry(hass)
Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for shelly using this method at custom_components/shelly/__init__.py, line 347: await self.hass.helpers.entity_registry.async_get_registry()

Logger: homeassistant.components.websocket_api.http.connection
Source: loader.py:694
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:27:45 (4 occurrences)
Last logged: 11:35:25

[548185787504] Error handling message: Unknown error (unknown_error)
[547883693392] Error handling message: Unknown error (unknown_error)
[547882963632] Error handling message: Unknown error (unknown_error)
[548240337936] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/shelly/ws_handler.py", line 25, in shelly_get_config
    resources = await async_get_translations(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load
    for translation_strings in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'l' not found.

```

**Comment by Masterz69** [comment]
On downloading 0.3.5 - looks Ok:
![image](https://user-images.githubusercontent.com/15225823/171992094-2cf72aa8-c3c8-4a69-88d4-f5aa6ccdb877.png)

**Comment by hakana** [comment]
Try to restart JA after det nstall S4H

**Comment by Masterz69** [comment]
![image](https://user-images.githubusercontent.com/15225823/172020024-3659bf4f-a4a4-4a9d-a2a9-5434ed5a5d5e.png)

Then

![image](https://user-images.githubusercontent.com/15225823/172020048-98e14b90-d408-4dd9-9185-8208ba7ca8a3.png)

Doing HA restart to new version take effect.

Now pressing CONFIGURE:
![image](https://user-images.githubusercontent.com/15225823/172020130-498a9174-53d3-4ba9-ab0f-9de2866c7df9.png)

THAT'S ALL, FOLKS. Configure page do NOT appear.....
![image](https://user-images.githubusercontent.com/15225823/172020162-4731eb1e-f007-43d9-b113-e35255ad18a0.png)

**Comment by Masterz69** [comment]
![image](https://user-images.githubusercontent.com/15225823/172020205-2a984b72-c972-4bfd-b92e-24b349bf8377.png)

```
Logger: pyShelly
Source: /usr/local/lib/python3.9/site-packages/pyShelly/utils.py:50
First occurred: 21:08:20 (94 occurrences)
Last logged: 21:10:56

Error receiving MQTT message, [Errno 104] Connection reset by peer, Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 92, in _loop self._connection.send(msg) ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 92, in _loop
    self._connection.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

Logger: pyShelly
Source: /usr/local/lib/python3.9/site-packages/pyShelly/utils.py:50
First occurred: 21:08:21 (60 occurrences)
Last logged: 21:10:57

Error receiving MQTT message, [Errno 104] Connection reset by peer, Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 29, in _loop head = b(self._connection.recv(1)) ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/mqtt_server.py", line 29, in _loop
    head = b(self._connection.recv(1))
ConnectionResetError: [Errno 104] Connection reset by peer




Logger: homeassistant.components.websocket_api.http.connection
Source: loader.py:694
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:09:17 (1 occurrences)
Last logged: 21:09:17

[547422525328] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/shelly/ws_handler.py", line 25, in shelly_get_config
    resources = await async_get_translations(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 317, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 222, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 237, in _async_load
    for translation_strings in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 157, in async_get_component_strings
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/loader.py", line 666, in async_get_integration
    integration = await _async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 694, in _async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'l' not found.
```

**Comment by hakana** [comment]
Look like it have something with translation, what language do you use?

**Comment by hakana** [comment]
I upgrade HA and got the same problem. I will have a look on it asap.

**Comment by Masterz69** [comment]
> Look like it have something with translation, what language do you use?

English.

**Comment by hakana** [comment]
Fixed and released in 1.0.0

**Comment by dnavidn** [comment]
Guerssing its related, but I can't integrate on 2022.6.2 following a clean install. Get a 500 internal server error when I click integrate. 

<img width="798" alt="Screenshot 2022-06-05 at 21 21 59" src="https://user-images.githubusercontent.com/65831715/172067112-ac7540a3-1f43-4edd-9b45-5952514da60d.png">

**Comment by fuskaps** [comment]
I also have a problem with error 500 :-(
![image](https://user-images.githubusercontent.com/49159343/172114806-1009ebb1-ad59-4ee3-8fde-46fb84a7b322.png)

**Comment by dnavidn** [comment]
Really, no one?

**Comment by silfax** [comment]
I can only confirm that I am experiencing the same issue (500 Internal Server Error). Found no solution yet.

**Comment by DaHype** [comment]
> I can only confirm that I am experiencing the same issue (500 Internal Server Error). Found no solution yet.

Same Here. I bought Shelly Plug s for my Photovoltaik for use in Home Assistant, but now i cant use it:-(

Did you found an solution???

**Comment by uwu-Felix** [comment]
For me the solution was to restart my docker container, after experiencing the same 500 Internal Server Error message.
