### ISSUE TITLE
ShellyPlus 2PM issue

### ISSUE THREAD

**Issue by ashmodai6** [StyraHem/ShellyForHASS#686]
**Environment**

ShellyForHASS release with the issue: 1.0.0
Last working ShellyForHASS release (if known):
Home Assistant Core release with the issue: Home Assistant Core 2022.6.2
Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant Supervisor 2022.06.3

**Describe the bug**

ShellyPlus 2PM seems does not work properly. 
![Screenshot 2022-06-07 at 13 08 41](https://user-images.githubusercontent.com/25221597/172365377-e199701f-2230-42e3-aa91-64dd4ce4a6e8.png)

**Expected behavior**

Capabilities listed properly...

**Comment by ashmodai6** [comment]
Just for completeness the switch is not unavailable. It can be accessed properly by the webui where everything seems to be working fine.
It is running the latest  Firmware version: 0.10.2 
Firmware build ID: 20220531-140502/0.10.2-g8a2ef01

And it is connected as well to my hass mosquito Mqtt server.

**Comment by FutureRap** [comment]
Have the same problem.
I solved it like this:
New HA without installing Shelly for Hass in the HACS. Just add the devices in the integration by hand. 
I hope this will be fixed in the next update

**Comment by FutureRap** [comment]
> Have the same problem. I solved it like this: New HA without installing Shelly for Hass in the HACS. Just add the devices in the integration by hand. I hope this will be fixed in the next update

AND: Connect to Shelly 2PM per direkt wifi 192.168.33.1 and update before implement via Shelly app.

**Comment by peterus** [comment]
are you trying to use the cover function? or just the two switches?

**Comment by FutureRap** [comment]
Cover...

**Comment by peterus** [comment]
duplicate of #684

**Comment by ashmodai6** [comment]
For me it was simply the two switches

**Comment by ReimPosDac** [comment]
The problem seems to persist... ShellyForHass doesn't recognize the device as a cover, even if it is defined as such.
With ShellyForHass removed, it works well.
Any clue or solution?

**Comment by mleiber** [comment]
Just installed 2 Shelly Plus 2PM for two roller shutters - like above, they are not detected as covers but as 2 switches. I deleted all traces of them and let them be re-discovered  by reloading the integration - problem persists.

I am running HA OS w/ core 2023.1.0 - problem was the same though for 2022.12.x.

I found this in the debug log when reloading the integration - maybe thia a clue of some sort.

`2023-01-05 10:36:00.018 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ShellyForHass for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 208, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!`

Btw, there's a myriad of  debug logs like this:

`2023-01-05 10:36:00.027 ERROR (MainThread) [homeassistant.components.light] Platform shelly does not generate unique IDs. ID _SHSW-1_40F6205A6788_gartenbeleuchtung_ost is already used by light.gartenbeleuchtung_ost - ignoring light.gartenbeleuchtung_ost`

**Comment by FutureRap** [comment]
Hi mleiber. Do you tried to go directy to the shelly device and turn the switch to shutter? Alle 2pm are shutter when you use for the firat time. so you have to go to the device first.
there are 2 ways. 
1. when the shelly is the first time running you can connect via wlan to them directly and vist the device with the ip 192.168.33.1 
2. 2. when your shelly is already in youre networt, visit the shelly whith that ip it has. when you dont know, you can go to your router or maybe you see the device in HA, so you visit the device from there.

**Comment by FutureRap** [comment]
Hmm...
Tricky.
1.Did you updatet the device first, before adding to HA?
2. Do you have installed Shelly for Hss via HACS? (sometime is the problem, that you have conflicts then) in that case i nstall HA NEW (deinstalling Shelly fot Hass is not enought) and then i add the devices by hand. Set in the config the commandoline for ahelly and i am NOT installimg Shelly for Hass... let me know

**Comment by mleiber** [comment]
re 1. - updated and configured the shelly devices before adding it to HA/ShellyForHass.
re 2. - Shelly For Hass has been installed via HACS. Not exactly sure what you mean by 'install HA NEW'. Can't simply do that, it's a sizeable installation of HA which I can't re-install easily w/o a lot of effort. No integration should require to do that - that would be a big drawback if so.

I'm also not sure what you mean by saying 'I am NOT installing Shelly for Hass' - do you use the native Shelly integration ? My problem is with Shelly For Hass and not with the native implementation (which I now consider moving to ...).

**Comment by apedance** [comment]
Having the same issue using Shelly Plus 2PM devices. Despite being configured as cover/roller/blind I see the devices as in the above mentioned screenshots.
Would be nice to stay with this integration.

**Comment by rinseringma** [comment]
Any updates on this? I do have the same issue.

**Comment by r77s** [comment]
Any news about this issue?

**Comment by hansblom-com** [comment]
Any updates on this issue?

**Comment by Ringo982** [comment]
Any update?? Why this issue is still opened? Is the integration mantenance still active?

**Comment by ebs-itsoft** [comment]
Any option for workaround with HA templates / configuration ?

**Comment by GK-hassio** [comment]
Still marked as open issue. 
I'm not able to use the workaround. Any solution planned for this issue?
- Device Profile set to COVER
