### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AnKloss** [StyraHem/ShellyForHASS#689]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/shelly/block.py:61 
Integration: Shelly smart home (documentation) 
First occurred: June 23, 2022, 9:07:06 AM (368149 occurrences) 
Last logged: 2:38:22 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
    entity.add_to_platform_abort()
  File "/config/custom_components/shelly/block.py", line 48, in add_to_platform_abort
    self._remove_handler()
  File "/config/custom_components/shelly/block.py", line 61, in _remove_handler
    self.instance.block_sensors.remove(self.ukey)
ValueError: list.remove(x): x not in list

Can fix this ?
mfg
Andreas

**Comment by AnKloss** [comment]
Hello, Yes, I Uninstaller Shelly For Hass, Uninstaller Shelly, reboot and use only Shelly for HA. Now works, no problem any more. MfgAndreas Sent from my Huawei phone-------- Original message --------From: Kévin ***@***.***>Date: Sat, Jul 9, 2022, 02:29To: StyraHem/ShellyForHASS ***@***.***>Cc: AnKloss ***@***.***>, Author ***@***.***>Subject: Re: [StyraHem/ShellyForHASS] [BUG] (Issue #689)
Hi
I got many issues with ShellyHASS plugin since the latest evrsion of HA :/ and I got the same issue than you.
Did you solved it ?
Thanks

**Comment by peterus** [comment]
duplicate of #268

**Comment by kevincaradant** [comment]
@AnKloss  thanks I will try to remove the plugin and install it again to see if it will be better.

@peterus I don't understand why you said it's duplicated. I don't see any similar things between both of them but maybe I miss something

**Comment by bcutter** [comment]
Unfortunately waiting is not an option for me. The log gets filled so freaking fast and the whole system gets quite some load only because of the Shelly integration. Thinking bout restoring some backups, if only the SQLite database would survive that... what a pity.
