### ISSUE TITLE
[BUG] async_setup

### ISSUE THREAD

**Issue by gatonero** [StyraHem/ShellyForHASS#692]
## Environment

- ShellyForHASS release with the issue: 1.0
- Last working ShellyForHASS release (if known): 0.3.5 ?
- Home Assistant Core release with the issue: 
- Operating environment (Home Assistant/Supervised/Docker/venv): 

## Traceback/Error logs

```txt

```

**Comment by gatonero** [comment]
I don't know why the log doesn't appear. Here it is again:
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/shelly/__init__.py:100
Integration: Shelly smart home (documentation)
First occurred: 18:36:25 (17 occurrences)
Last logged: 18:36:25

Error setting up entry DW2-07 for shelly
Error setting up entry DW2-02 for shelly
Error setting up entry TRV-Kueche for shelly
Error setting up entry Plug-01 for shelly
Error setting up entry Plug-02 for shelly
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/shelly/__init__.py", line 100, in async_setup_entry
    conf = CONFIG_SCHEMA_ROOT(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['host']
`
