### ISSUE TITLE
[BUG] Can't configure under HA Core 2022.7.6[BUG]

### ISSUE THREAD

**Issue by DaHype** [StyraHem/ShellyForHASS#699]
Not possible to configurate it.
![Screenshot_20220726-140650_Home Assistant](https://user-images.githubusercontent.com/102579433/181004579-f6ddb860-c714-46f5-979d-8047cd70c642.jpg)

**Comment by StephanGR** [comment]
Got this error : 
```


Logger: pyShelly
Source: /usr/local/lib/python3.10/site-packages/pyShelly/coap.py:31
First occurred: 30 juillet 2022 à 01:46:55 (1 occurrences)
Last logged: 30 juillet 2022 à 01:46:55
Can't setup CoAP listener

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyShelly/coap.py", line 28, in start
    self._init_socket()
  File "/usr/local/lib/python3.10/site-packages/pyShelly/coap.py", line 53, in _init_socket
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
OSError: [Errno 19] No such device
```

**Comment by giadamosi** [comment]
Same error here

**Comment by DaHype** [comment]
> Same error here

Thanks for Confirm

I really hope that @hakana can fix it soon.

**Comment by gradvis** [comment]
core-2022.7.7

I get error too:

`Logger: aiohttp.server
Source: config_entries.py:229
First occurred: 12:38:44 (4 occurrences)
Last logged: 12:42:05

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 168, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 95, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 747, in async_finish_flow
    entry = ConfigEntry(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 229, in __init__
    self.data = MappingProxyType(data)
TypeError: mappingproxy() argument must be a mapping, not NoneType
`

**Comment by hakana** [comment]
Is it working if you select Shelly from the sidebar or go to the URL /shelly/config ?

**Comment by DaHype** [comment]
> Is it working if you select Shelly from the sidebar or go to the URL /shelly/config ?

No. Currently i use MQTT from Shelly Device in Home Assistant. It´s working fine. All Sensors working with MQTT.
Your Integration always gives the Error 500.  Of course also when i deactivate MQTT on the Shelly Device.

**Comment by hakana** [comment]
> > Is it working if you select Shelly from the sidebar or go to the URL /shelly/config ?
> 
> No. Currently i use MQTT from Shelly Device in Home Assistant. It´s working fine. All Sensors working with MQTT.
> Your Integration always gives the Error 500.  Of course also when i deactivate MQTT on the Shelly Device.

Can you see an error message or only 500 error code? Can you take a screen show?

**Comment by DaHype** [comment]
Show only "500 Internal Server Error, the Server got itself in trouble"

**Comment by WhiteWolf84** [comment]
I've the same error:

`Logger: aiohttp.server
Source: config_entries.py:233
First occurred: 20:55:54 (1 occurrences)
Last logged: 20:55:54

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 168, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 95, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 759, in async_finish_flow
    entry = ConfigEntry(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 233, in __init__
    self.data = MappingProxyType(data)
TypeError: mappingproxy() argument must be a mapping, not NoneType
`

**Comment by Schult0r** [comment]
Same Error here.
![shellyforhass_error500](https://user-images.githubusercontent.com/94725726/184883803-0d63343a-29f8-4a74-9201-c39a0e34bf0a.png)

**Comment by D-Bullock** [comment]
I managed to work around it by manually adding a new "Shelly" integration, choosing new instance. The new instance correclty found my shelly devices.
Hope this helps someone
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3475857/192092277-54a99eef-4e47-4da5-b35f-d6a65b538dcf.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/3475857/192092297-0319b43e-a45e-450f-8ba3-9f2ca28107b2.png">

**Comment by SpeedmaxX** [comment]
didn't work on my side, sorry. Nothing happens, when clicking "set up an other instance of Shelly smart home"
Any other ideas?

**Comment by basziee** [comment]
> didn't work on my side, sorry. Nothing happens, when clicking "set up an other instance of Shelly smart home" Any other ideas?

I have the same problem. in the console it say's `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'supported_by')`
I installed 1.0.1 and now it's working

**Comment by stu55sy** [comment]
> 

Same issue. This work araound has worked for me

**Comment by Trzinka** [comment]
I'm not sure what this error means, but it keeps showing me!
```
Log Details (ERROR)
Logger: pyShelly
Source: /usr/local/lib/python3.11/site-packages/pyShelly/coap.py:31
First occurred: 12:10:59 (1 occurrences)
Last logged: 12:10:59

Can't setup CoAP listener
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyShelly/coap.py", line 28, in start
    self._init_socket()
  File "/usr/local/lib/python3.11/site-packages/pyShelly/coap.py", line 53, in _init_socket
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
OSError: [Errno 19] No such device
```
