### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by openmisak** [StyraHem/ShellyForHASS#735]
## Environment

- ShellyForHASS release with the issue: 1.0.2
- Last working ShellyForHASS release (if known): 1.0.1
- Home Assistant Core release with the issue: 2022.12.7
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant

## Describe the bug

Shelly devices 3EM and 2.5 became Unavailable after update to the version 1.0.2.

## Steps to Reproduce

Update from HACS Integration menu from the version 1.0.1 to the version 1.0.2

## Expected behavior

All Shelly devices should be available and communicating after the new version update and HA restart.

## Traceback/Error logs

```This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/shelly/__init__.py:100 
Integration: Shelly smart home (documentation) 
First occurred: 13:01:49 (3 occurrences) 
Last logged: 13:01:49

Error setting up entry Shelly zaluzie LEVA for shelly
Error setting up entry Shelly zaluzie PRAVA for shelly
Error setting up entry Shelly 3EM for shelly
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/shelly/__init__.py", line 100, in async_setup_entry
    conf = CONFIG_SCHEMA_ROOT(data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['host']


```

**Comment by jasgrif11** [comment]
I'm also seeing this same behaviour
<img width="279" alt="screenshot_1007" src="https://user-images.githubusercontent.com/5337522/210436106-b2391a16-31f2-4f98-ac6f-b8952618ddfb.png">

**Comment by me1299** [comment]
I'm afraid of upgrading Home Assistant because I think things will break. Also the latest commit was 4 months ago. Is it time to switch to the official integration or do I have to practice more patience?

**Comment by tomas0620** [comment]
same for me. 
Device: Shelly PLUS 1 PM

**Comment by gatonero** [comment]
This happened to me after upgrading from 1.0.2 to 1.0.5. All shelly devices are broken and brought a lot of work to get them running again. This happened to me for the second time using this integration.

**Comment by hakana** [comment]
Try to restart HA and see if that helps.

**Comment by gatonero** [comment]
That didn't help. I switched back to the official integration.

**Comment by woopstar** [comment]
I see the same issue. Tried downgrading to 1.0.2 from 1.0.5 and the error persists.

**Comment by bencebodnar** [comment]
Same issue, all of my shelly integrated devices offline. Only help is the HomeAssistant backup restore.

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/shelly/__init__.py:100
> Integration: Shelly smart home (documentation)
> First occurred: 6:37:32 PM (25 occurrences)
> Last logged: 6:37:32 PM
> 
> Error setting up entry Nappali-szoba-bal for shelly
> Error setting up entry shellyplusht-szoba for shelly
> Error setting up entry shellyplusht-nappali for shelly
> Error setting up entry shellyht-fürdő for shelly
> Error setting up entry Gepesz kapcsolo for shelly
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/shelly/__init__.py", line 100, in async_setup_entry
>     conf = CONFIG_SCHEMA_ROOT(data)
>   File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
>     return base_validate(path, iteritems(data), out)
>   File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
>     raise er.MultipleInvalid(errors)
> voluptuous.error.MultipleInvalid: extra keys not allowed @ data['host']
>

**Comment by dan-dan81** [comment]
I am seeing the same issue, with attempts to roll back to 1.0.1 not resolving. 

Is this issue being worked on?

**Comment by seb-koch** [comment]
I got the exact same issue and now all my shelly's are offline. Help is appreciated. Dear maintainers, please let us know if this issue is already somewhat tackled. Thanks

**Comment by bencebodnar** [comment]
@seb-koch the only help is the rollback for the backup which contains the previous (1.0.2 for me) working state.
