### ISSUE TITLE
[BUG] Python issues?

### ISSUE THREAD

**Issue by alfureu** [StyraHem/ShellyForHASS#773]
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): no idea
- Home Assistant Core release with the issue: 2024.1.5
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker (latest)

## Describe the bug
ShellyForHASS keeps crashing after roughly 24h of running. It was never doing it before, so I guess it is something that got introduced with the most recent update

## Steps to Reproduce
Just run ShellyForHASS in a HA docker on a slower machine, it will happen. 

## Expected behavior
Should not crash, as with previous versions

## Screenshots
N/A

## Traceback/Error logs

```txt
The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/pyShelly/__init__.py", line 374, in _update_loop

    self.check_by_ip()

  File "/usr/local/lib/python3.11/site-packages/pyShelly/__init__.py", line 241, in check_by_ip

    ip_addr = self._mdns.get_ip(*data['id'].split('|'))

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pyShelly/mdns.py", line 19, in get_ip

    info = self._zeroconf.get_service_info(type, name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 266, in get_service_info

    if info.request(self, timeout, question_type):

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "src/zeroconf/_services/info.py", line 778, in zeroconf._services.info.ServiceInfo.request

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 117, in run_coro_with_timeout

    raise EventLoopBlocked from ex

zeroconf._exceptions.EventLoopBlocked

2024-01-26 22:20:54.537 ERROR (Update loop) [pyShelly] Error update loop, , Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 113, in run_coro_with_timeout

    return asyncio.run_coroutine_threadsafe(aw, loop).result(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 458, in result

    raise TimeoutError()

TimeoutError


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/pyShelly/__init__.py", line 374, in _update_loop

    self.check_by_ip()

  File "/usr/local/lib/python3.11/site-packages/pyShelly/__init__.py", line 241, in check_by_ip

    ip_addr = self._mdns.get_ip(*data['id'].split('|'))

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pyShelly/mdns.py", line 19, in get_ip

    info = self._zeroconf.get_service_info(type, name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 266, in get_service_info

    if info.request(self, timeout, question_type):

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "src/zeroconf/_services/info.py", line 778, in zeroconf._services.info.ServiceInfo.request

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 117, in run_coro_with_timeout

    raise EventLoopBlocked from ex

zeroconf._exceptions.EventLoopBlocked

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 113, in run_coro_with_timeout

    return asyncio.run_coroutine_threadsafe(aw, loop).result(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 458, in result

    raise TimeoutError()

TimeoutError


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/pyShelly/__init__.py", line 374, in _update_loop

    self.check_by_ip()

  File "/usr/local/lib/python3.11/site-packages/pyShelly/__init__.py", line 241, in check_by_ip

    ip_addr = self._mdns.get_ip(*data['id'].split('|'))

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pyShelly/mdns.py", line 19, in get_ip

    info = self._zeroconf.get_service_info(type, name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 266, in get_service_info

    if info.request(self, timeout, question_type):

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "src/zeroconf/_services/info.py", line 778, in zeroconf._services.info.ServiceInfo.request

  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 117, in run_coro_with_timeout

    raise EventLoopBlocked from ex

zeroconf._exceptions.EventLoopBlocked

```

## Additional context
Running HA as a docker: `homeassistant/home-assistant:latest`

**Comment by maxbec** [comment]
No fix yet?
