### ISSUE TITLE
Device displayed but not responding

### ISSUE THREAD

**Issue by MDLefevere** [StyraHem/ShellyForHASS#89]
Hi All,

I've setup some Shelly1's and installed ShellyForHass. I followed the tutorial and enabled "Shelly:" in configuration.yalm.

The strange thing is that my device correctly shows up but it is not responding to any actions from Hassio.

It comes with the following error:

```
Error http GET: http://192.168.1.50/relay/0?turn=on Extra data: line 1 column 5 (char 4) Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by hakana** [comment]
Do you have restricted login on your shellies?

**Comment by MDLefevere** [comment]
Yeah i have. Do i need to configure that somewere else?

**Comment by hakana** [comment]
You need to enter the user and password in config under shelly:. See doc.

**Comment by MDLefevere** [comment]
That simple 👍 
Thanks. It's working like a charm now !

**Comment by hakana** [comment]
Great!
