### ISSUE TITLE
Component working, but "expecting value"

### ISSUE THREAD

**Issue by Engelbert** [StyraHem/ShellyForHASS#93]
I think everything is working, component picks up the shellys correctly. But it can't seem to control them.

_Log entry:_

**Log Details (ERROR)**
```
Error http GET: http://169.254.10.1/roller/0?go=close Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hakana** [comment]
Do you have restricted login on the device? Then you must enter user and password in config under shelly.

**Comment by Engelbert** [comment]
is it supposed to be this ip?  **169.254.10.1**
because my network is **192.168.1.x**

I have tried the username/password and it is all set as it should be I think.

conf below

```
shelly:
  username: bert
  password: bert
  discovery: false  #add all devices (default)
  #igmp_fix: true
  devices:  #configure devices
    - id: "00839f"
      #light_switch: true  #add this switch as a light
    - id: "E4DF29"
    - id: "e665e4"
    - id: "e62aff"
```

**Comment by hakana** [comment]
It look like there is some problem with your DHCP. The device got this ip when not received an ip from DHCP server.

**Comment by Engelbert** [comment]
i have them set on a static ip should I remove that and try again?

**Comment by hakana** [comment]
Can't tell why it reported this ip.

You should be able to use static ip but make sure to exclude it from any DHCP ranges.

**Comment by Engelbert** [comment]
http://169.254.10.1/
that is the ip it has given to all the shellys to send commands.
strangely the sensors work like they should and use the good ip.

`Error http GET: http://169.254.10.1/roller/0?go=stop Expecting value: line 1 column 1 (char 0) `

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

removed username and password from my config 

```
2019-11-13 22:50:33 ERROR (Thread-2) [pyShelly] Error http GET: http://192.168.1.118/settings Extra data: line 1 column 5 (char 4) Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

all testing done on a new up to date install of hassio
